package postgres

import (
	"context"
	"errors"
	"fmt"
	"strconv"
	"strings"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/andreasoentoro/hearth/api/internal/domain"
	"github.com/andreasoentoro/hearth/api/internal/usecase"
)

// BrowseRepo reads the database's own shape and contents for the operator's
// admin surface.
//
// Every other repository here is generated by sqlc from a static query in
// queries/. This one builds its SELECT list and FROM clause at call time
// from the catalogue, so the SQL lives here as strings, under two rules:
//
//   - No value from a request is ever concatenated into SQL. A table name is
//     matched against information_schema first (which also enforces what
//     this role may see) and quoted with pgx.Identifier second. Everything
//     else travels as a bind parameter.
//   - A redacted column is never selected: its place in the SELECT list is a
//     parameter, so the secret bytes never leave Postgres.
type BrowseRepo struct{ pool *pgxpool.Pool }

// Its own assertion here rather than in convert.go's block, next to the
// reasoning it has to hold up.
var _ usecase.DatabaseBrowser = (*BrowseRepo)(nil)

// NewBrowseRepo takes a *ReadOnlyDB and nothing else. The type is what stops
// this being constructed over the read-write pool by mistake; there is no
// constructor that would accept one.
func NewBrowseRepo(db *ReadOnlyDB) *BrowseRepo { return &BrowseRepo{pool: db.Pool()} }

func (r *BrowseRepo) Tables(ctx context.Context) ([]usecase.TableInfo, error) {
	names, err := r.tableNames(ctx)
	if err != nil {
		return nil, err
	}
	columns, err := r.allColumns(ctx)
	if err != nil {
		return nil, err
	}
	counts, err := r.rowCounts(ctx, names)
	if err != nil {
		return nil, err
	}

	tables := make([]usecase.TableInfo, 0, len(names))
	for i, name := range names {
		tables = append(tables, usecase.TableInfo{
			Name:     name,
			RowCount: counts[i],
			Columns:  columns[name],
		})
	}
	return tables, nil
}

func (r *BrowseRepo) Rows(ctx context.Context, table string, limit, offset int) (usecase.RowPage, error) {
	columns, err := r.columnsOf(ctx, table)
	if err != nil {
		return usecase.RowPage{}, err
	}
	// Schema-qualified to match columnsOf and orderBy, which also pin
	// 'public'. An unqualified name here would resolve through search_path
	// instead, so two references to "the same table" could silently name
	// different relations.
	quoted := pgx.Identifier{"public", table}.Sanitize()

	var total int64
	if err := r.pool.QueryRow(ctx, `SELECT count(*) FROM `+quoted).Scan(&total); err != nil {
		return usecase.RowPage{}, browseErr(err, "count rows")
	}

	orderBy, err := r.orderBy(ctx, table)
	if err != nil {
		return usecase.RowPage{}, err
	}

	// Parameters are numbered as they are added, so the placeholder count can
	// never drift from the argument list. A hand-numbered scheme risks a bind
	// error on some table nobody tested.
	args := make([]any, 0, len(columns)+2)
	placeholder := func(v any) string {
		args = append(args, v)
		return "$" + strconv.Itoa(len(args))
	}

	list := make([]string, 0, len(columns))
	for _, c := range columns {
		if c.Redacted {
			list = append(list, placeholder(domain.RedactedCell)+"::text")
			continue
		}
		list = append(list, "coalesce("+pgx.Identifier{c.Name}.Sanitize()+"::text, "+placeholder(domain.NullCell)+")")
	}

	query := "SELECT " + strings.Join(list, ", ") +
		" FROM " + quoted +
		" ORDER BY " + orderBy +
		" LIMIT " + placeholder(limit) +
		" OFFSET " + placeholder(offset)

	rows, err := r.pool.Query(ctx, query, args...)
	if err != nil {
		return usecase.RowPage{}, browseErr(err, "read rows")
	}
	defer rows.Close()

	out := make([][]string, 0, limit)
	for rows.Next() {
		cells := make([]string, len(columns))
		dest := make([]any, len(columns))
		for i := range cells {
			dest[i] = &cells[i]
		}
		if err := rows.Scan(dest...); err != nil {
			return usecase.RowPage{}, browseErr(err, "scan row")
		}
		out = append(out, cells)
	}
	if err := rows.Err(); err != nil {
		return usecase.RowPage{}, browseErr(err, "read rows")
	}

	return usecase.RowPage{
		Columns: columns,
		Rows:    out,
		Total:   total,
		Limit:   limit,
		Offset:  offset,
	}, nil
}

// columnsOf doubles as the table's existence check and, since
// information_schema is filtered per role, as a privilege check: a table the
// GRANT missed answers "no such table" instead of a raw Postgres permission
// error the operator has to interpret.
func (r *BrowseRepo) columnsOf(ctx context.Context, table string) ([]usecase.ColumnInfo, error) {
	rows, err := r.pool.Query(ctx, `
		SELECT c.column_name, c.data_type, c.udt_name
		FROM information_schema.columns c
		JOIN information_schema.tables t
		  ON t.table_schema = c.table_schema AND t.table_name = c.table_name
		WHERE c.table_schema = 'public'
		  AND t.table_type = 'BASE TABLE'
		  AND c.table_name = $1
		ORDER BY c.ordinal_position`, table)
	if err != nil {
		return nil, browseErr(err, "read columns")
	}
	defer rows.Close()

	var columns []usecase.ColumnInfo
	for rows.Next() {
		var name, dataType, udtName string
		if err := rows.Scan(&name, &dataType, &udtName); err != nil {
			return nil, browseErr(err, "scan column")
		}
		columns = append(columns, usecase.ColumnInfo{
			Name:     name,
			DataType: displayType(dataType, udtName),
			Redacted: domain.ColumnIsRedacted(name, dataType, udtName),
		})
	}
	if err := rows.Err(); err != nil {
		return nil, browseErr(err, "read columns")
	}
	// No columns means no such table for this role, and that is the only
	// path by which a name from a URL is ever refused -- the name has still
	// not touched a query except as a bind parameter.
	if len(columns) == 0 {
		return nil, domain.ErrNotFound
	}
	return columns, nil
}

// orderBy makes pagination stable: LIMIT/OFFSET without ORDER BY lets
// Postgres return rows in any order, so page 2 could repeat or skip rows.
//
// The primary key orders when there is one; ctid is the fallback -- stable
// within a read, but arbitrary. This is not a sort the operator controls.
func (r *BrowseRepo) orderBy(ctx context.Context, table string) (string, error) {
	rows, err := r.pool.Query(ctx, `
		SELECT a.attname
		FROM pg_index i
		JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY (i.indkey)
		WHERE i.indrelid = to_regclass('public.' || quote_ident($1))
		  AND i.indisprimary
		ORDER BY array_position(i.indkey::int2[], a.attnum)`, table)
	if err != nil {
		return "", browseErr(err, "read the primary key")
	}
	defer rows.Close()

	var keys []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return "", browseErr(err, "scan the primary key")
		}
		keys = append(keys, pgx.Identifier{name}.Sanitize())
	}
	if err := rows.Err(); err != nil {
		return "", browseErr(err, "read the primary key")
	}
	if len(keys) == 0 {
		return "ctid", nil
	}
	return strings.Join(keys, ", "), nil
}

func (r *BrowseRepo) tableNames(ctx context.Context) ([]string, error) {
	rows, err := r.pool.Query(ctx, `
		SELECT table_name FROM information_schema.tables
		WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
		ORDER BY table_name`)
	if err != nil {
		return nil, browseErr(err, "list tables")
	}
	defer rows.Close()

	var names []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, browseErr(err, "scan table name")
		}
		names = append(names, name)
	}
	return names, browseErr(rows.Err(), "list tables")
}

func (r *BrowseRepo) allColumns(ctx context.Context) (map[string][]usecase.ColumnInfo, error) {
	rows, err := r.pool.Query(ctx, `
		SELECT table_name, column_name, data_type, udt_name
		FROM information_schema.columns
		WHERE table_schema = 'public'
		ORDER BY table_name, ordinal_position`)
	if err != nil {
		return nil, browseErr(err, "list columns")
	}
	defer rows.Close()

	byTable := map[string][]usecase.ColumnInfo{}
	for rows.Next() {
		var table, name, dataType, udtName string
		if err := rows.Scan(&table, &name, &dataType, &udtName); err != nil {
			return nil, browseErr(err, "scan column")
		}
		byTable[table] = append(byTable[table], usecase.ColumnInfo{
			Name:     name,
			DataType: displayType(dataType, udtName),
			Redacted: domain.ColumnIsRedacted(name, dataType, udtName),
		})
	}
	return byTable, browseErr(rows.Err(), "list columns")
}

// displayType is the type name the Columns pane shows an operator.
//
// information_schema.data_type is human-readable ("timestamp with time
// zone") for most types, but an array reports "ARRAY" and a domain or
// extension type reports "USER-DEFINED" -- both categories, not names. Those
// two take udt_name instead, turning its leading underscore ("_text") back
// into the [] the migration was written with.
//
// Passing data_type through in the default arm is not a fail-closed
// violation: this only decides a label. Redaction is decided separately by
// domain.ColumnIsRedacted.
func displayType(dataType, udtName string) string {
	switch dataType {
	case "ARRAY":
		return strings.TrimPrefix(udtName, "_") + "[]"
	case "USER-DEFINED":
		return udtName
	default:
		return dataType
	}
}

// rowCounts counts every table in one statement instead of one round trip
// per table.
//
// Counts are exact, not the pg_class.reltuples estimate: this screen's job
// is showing what is actually there, and these tables are small enough
// that an exact count fits the timeout -- if one ever grows past it, the
// resulting failure is the signal to revisit this.
//
// Positional rather than labelled -- answers come back in the order the
// names went in -- so a table name is never quoted as a string literal.
func (r *BrowseRepo) rowCounts(ctx context.Context, names []string) ([]int64, error) {
	if len(names) == 0 {
		return nil, nil
	}
	parts := make([]string, 0, len(names))
	for _, name := range names {
		// Schema-qualified for the same reason Rows is: the names came from
		// information_schema filtered to 'public', so the count must be of
		// that relation and not of whatever search_path finds first.
		parts = append(parts, "(SELECT count(*) FROM "+pgx.Identifier{"public", name}.Sanitize()+")")
	}

	counts := make([]int64, len(names))
	dest := make([]any, len(names))
	for i := range counts {
		dest[i] = &counts[i]
	}
	if err := r.pool.QueryRow(ctx, "SELECT "+strings.Join(parts, ", ")).Scan(dest...); err != nil {
		return nil, browseErr(err, "count rows")
	}
	return counts, nil
}

// browseErr keeps domain.ErrNotFound intact and turns everything else into
// ErrBrowseUnavailable, so the HTTP layer can distinguish "no such table"
// from "the reader is broken". The op phrase is kept for the log; the
// sentinel is what callers match on.
func browseErr(err error, op string) error {
	if err == nil {
		return nil
	}
	if translated := translate(err, op); errors.Is(translated, domain.ErrNotFound) {
		return domain.ErrNotFound
	}
	return fmt.Errorf("%w: %s: %v", usecase.ErrBrowseUnavailable, op, err)
}
