// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    household_id, nickname, type, owner_membership_id,
    opening_balance_minor, opening_balance_currency, opening_balance_as_of,
    count_toward_net_worth, visible_to_limited_members
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, household_id, nickname, type, owner_membership_id, opening_balance_minor, opening_balance_currency, opening_balance_as_of, count_toward_net_worth, visible_to_limited_members, archived_at, created_at
`

type CreateAccountParams struct {
	HouseholdID             pgtype.UUID
	Nickname                string
	Type                    string
	OwnerMembershipID       pgtype.UUID
	OpeningBalanceMinor     int64
	OpeningBalanceCurrency  string
	OpeningBalanceAsOf      pgtype.Date
	CountTowardNetWorth     bool
	VisibleToLimitedMembers bool
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.HouseholdID,
		arg.Nickname,
		arg.Type,
		arg.OwnerMembershipID,
		arg.OpeningBalanceMinor,
		arg.OpeningBalanceCurrency,
		arg.OpeningBalanceAsOf,
		arg.CountTowardNetWorth,
		arg.VisibleToLimitedMembers,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Nickname,
		&i.Type,
		&i.OwnerMembershipID,
		&i.OpeningBalanceMinor,
		&i.OpeningBalanceCurrency,
		&i.OpeningBalanceAsOf,
		&i.CountTowardNetWorth,
		&i.VisibleToLimitedMembers,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT a.id, a.household_id, a.nickname, a.type, a.owner_membership_id, a.opening_balance_minor, a.opening_balance_currency, a.opening_balance_as_of, a.count_toward_net_worth, a.visible_to_limited_members, a.archived_at, a.created_at, u.display_name AS owner_name,
       -- See ListAccounts above for why this is two filtered sums with
       -- >= and why the incoming side prefers received_amount_minor.
       -- Get and List must compute this the same way, or the two disagree
       -- on the same account's balance.
       (a.opening_balance_minor
        - COALESCE((SELECT SUM(t.amount_minor) FROM transactions t
                    WHERE t.from_account_id = a.id
                      AND t.occurred_on >= a.opening_balance_as_of), 0)
        + COALESCE((SELECT SUM(COALESCE(t.received_amount_minor, t.amount_minor))
                    FROM transactions t
                    WHERE t.to_account_id = a.id
                      AND t.occurred_on >= a.opening_balance_as_of), 0)
       )::bigint AS balance_minor
FROM accounts a
LEFT JOIN memberships m ON m.id = a.owner_membership_id
LEFT JOIN users u ON u.id = m.user_id
WHERE a.household_id = $1 AND a.id = $2
`

type GetAccountParams struct {
	HouseholdID pgtype.UUID
	ID          pgtype.UUID
}

type GetAccountRow struct {
	Account      Account
	OwnerName    *string
	BalanceMinor int64
}

// GetAccount scopes by household_id as well as id, like every query in this
// file: id alone would let a caller in one household read another's row by
// guessing a uuid, and the HTTP session already supplies the household id.
func (q *Queries) GetAccount(ctx context.Context, arg GetAccountParams) (GetAccountRow, error) {
	row := q.db.QueryRow(ctx, getAccount, arg.HouseholdID, arg.ID)
	var i GetAccountRow
	err := row.Scan(
		&i.Account.ID,
		&i.Account.HouseholdID,
		&i.Account.Nickname,
		&i.Account.Type,
		&i.Account.OwnerMembershipID,
		&i.Account.OpeningBalanceMinor,
		&i.Account.OpeningBalanceCurrency,
		&i.Account.OpeningBalanceAsOf,
		&i.Account.CountTowardNetWorth,
		&i.Account.VisibleToLimitedMembers,
		&i.Account.ArchivedAt,
		&i.Account.CreatedAt,
		&i.OwnerName,
		&i.BalanceMinor,
	)
	return i, err
}

const listAccountMonthlyMovements = `-- name: ListAccountMonthlyMovements :many
SELECT account_id,
       month,
       SUM(delta_minor)::bigint AS delta_minor,
       currency
FROM (
    SELECT t.from_account_id AS account_id,
           DATE_TRUNC('month', t.occurred_on)::date AS month,
           -t.amount_minor AS delta_minor,
           a.opening_balance_currency AS currency
    FROM transactions t
    JOIN accounts a ON a.id = t.from_account_id
    WHERE a.household_id = $1
      AND t.occurred_on >= a.opening_balance_as_of
      AND t.occurred_on >= $2::date
    UNION ALL
    SELECT t.to_account_id,
           DATE_TRUNC('month', t.occurred_on)::date,
           COALESCE(t.received_amount_minor, t.amount_minor),
           a.opening_balance_currency
    FROM transactions t
    JOIN accounts a ON a.id = t.to_account_id
    WHERE a.household_id = $1
      AND t.occurred_on >= a.opening_balance_as_of
      AND t.occurred_on >= $2::date
) movements
GROUP BY account_id, month, currency
ORDER BY account_id, month
`

type ListAccountMonthlyMovementsParams struct {
	HouseholdID pgtype.UUID
	Since       pgtype.Date
}

type ListAccountMonthlyMovementsRow struct {
	AccountID  pgtype.UUID
	Month      pgtype.Date
	DeltaMinor int64
	Currency   string
}

// ListAccountMonthlyMovements backs the twelve-month trend: one row per
// account per calendar month with any movement, in that account's own
// currency. No conversion happens here and none can: the FX provider lives
// in the usecase layer (MonthTotalsQuery says the same).
//
// The filter mirrors ListAccounts's balance expression, including the
// missing upper bound on occurred_on. A transaction dated after today is
// refused when it is written, but one stored earlier may be, and it is
// already inside the anchor balance. It must stay identical: the trend walks
// backwards from AccountView.Balance by subtracting these deltas, so any
// mismatch makes older bars disagree with the headline figure. The service
// buckets any later month into the current one.
func (q *Queries) ListAccountMonthlyMovements(ctx context.Context, arg ListAccountMonthlyMovementsParams) ([]ListAccountMonthlyMovementsRow, error) {
	rows, err := q.db.Query(ctx, listAccountMonthlyMovements, arg.HouseholdID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountMonthlyMovementsRow
	for rows.Next() {
		var i ListAccountMonthlyMovementsRow
		if err := rows.Scan(
			&i.AccountID,
			&i.Month,
			&i.DeltaMinor,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccounts = `-- name: ListAccounts :many

SELECT a.id, a.household_id, a.nickname, a.type, a.owner_membership_id, a.opening_balance_minor, a.opening_balance_currency, a.opening_balance_as_of, a.count_toward_net_worth, a.visible_to_limited_members, a.archived_at, a.created_at, u.display_name AS owner_name,
       -- balance_minor is opening balance plus every transaction dated ON OR
       -- AFTER opening_balance_as_of (spec 2026-07-30-hearth-finance-fixes):
       -- the opening balance is the figure at the START of that day, so a
       -- same-day transaction still moves it, while an earlier one is
       -- already baked into that figure.
       --
       -- Two filtered sums, not one, because an account can be both a
       -- transfer's source and another transfer's destination. The incoming
       -- side prefers received_amount_minor -- what actually landed, in this
       -- account's currency -- over amount_minor, which is in the sender's
       -- currency; no conversion happens here or can, since everything above
       -- is already in this account's own currency.
       (a.opening_balance_minor
        - COALESCE((SELECT SUM(t.amount_minor) FROM transactions t
                    WHERE t.from_account_id = a.id
                      AND t.occurred_on >= a.opening_balance_as_of), 0)
        + COALESCE((SELECT SUM(COALESCE(t.received_amount_minor, t.amount_minor))
                    FROM transactions t
                    WHERE t.to_account_id = a.id
                      AND t.occurred_on >= a.opening_balance_as_of), 0)
       )::bigint AS balance_minor
FROM accounts a
LEFT JOIN memberships m ON m.id = a.owner_membership_id
LEFT JOIN users u ON u.id = m.user_id
WHERE a.household_id = $1 AND a.archived_at IS NULL
ORDER BY a.created_at
`

type ListAccountsRow struct {
	Account      Account
	OwnerName    *string
	BalanceMinor int64
}

// ListAccounts and ListAccountsIncludingArchived are two queries, not one
// with a boolean parameter, because a `WHERE archived_at IS NULL OR $2`
// predicate would not use the partial index accounts_household_idx that the
// live-only form does.
//
// The LEFT JOIN lets a shared account (owner_membership_id IS NULL) come
// back as a row with a NULL owner name rather than vanishing.
func (q *Queries) ListAccounts(ctx context.Context, householdID pgtype.UUID) ([]ListAccountsRow, error) {
	rows, err := q.db.Query(ctx, listAccounts, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountsRow
	for rows.Next() {
		var i ListAccountsRow
		if err := rows.Scan(
			&i.Account.ID,
			&i.Account.HouseholdID,
			&i.Account.Nickname,
			&i.Account.Type,
			&i.Account.OwnerMembershipID,
			&i.Account.OpeningBalanceMinor,
			&i.Account.OpeningBalanceCurrency,
			&i.Account.OpeningBalanceAsOf,
			&i.Account.CountTowardNetWorth,
			&i.Account.VisibleToLimitedMembers,
			&i.Account.ArchivedAt,
			&i.Account.CreatedAt,
			&i.OwnerName,
			&i.BalanceMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountsIncludingArchived = `-- name: ListAccountsIncludingArchived :many
SELECT a.id, a.household_id, a.nickname, a.type, a.owner_membership_id, a.opening_balance_minor, a.opening_balance_currency, a.opening_balance_as_of, a.count_toward_net_worth, a.visible_to_limited_members, a.archived_at, a.created_at, u.display_name AS owner_name,
       -- See ListAccounts above for why this is two filtered sums with
       -- >= and why the incoming side prefers received_amount_minor.
       (a.opening_balance_minor
        - COALESCE((SELECT SUM(t.amount_minor) FROM transactions t
                    WHERE t.from_account_id = a.id
                      AND t.occurred_on >= a.opening_balance_as_of), 0)
        + COALESCE((SELECT SUM(COALESCE(t.received_amount_minor, t.amount_minor))
                    FROM transactions t
                    WHERE t.to_account_id = a.id
                      AND t.occurred_on >= a.opening_balance_as_of), 0)
       )::bigint AS balance_minor
FROM accounts a
LEFT JOIN memberships m ON m.id = a.owner_membership_id
LEFT JOIN users u ON u.id = m.user_id
WHERE a.household_id = $1
ORDER BY a.archived_at NULLS FIRST, a.created_at
`

type ListAccountsIncludingArchivedRow struct {
	Account      Account
	OwnerName    *string
	BalanceMinor int64
}

func (q *Queries) ListAccountsIncludingArchived(ctx context.Context, householdID pgtype.UUID) ([]ListAccountsIncludingArchivedRow, error) {
	rows, err := q.db.Query(ctx, listAccountsIncludingArchived, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountsIncludingArchivedRow
	for rows.Next() {
		var i ListAccountsIncludingArchivedRow
		if err := rows.Scan(
			&i.Account.ID,
			&i.Account.HouseholdID,
			&i.Account.Nickname,
			&i.Account.Type,
			&i.Account.OwnerMembershipID,
			&i.Account.OpeningBalanceMinor,
			&i.Account.OpeningBalanceCurrency,
			&i.Account.OpeningBalanceAsOf,
			&i.Account.CountTowardNetWorth,
			&i.Account.VisibleToLimitedMembers,
			&i.Account.ArchivedAt,
			&i.Account.CreatedAt,
			&i.OwnerName,
			&i.BalanceMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const membershipBelongsToHousehold = `-- name: MembershipBelongsToHousehold :one
SELECT EXISTS (
    SELECT 1 FROM memberships WHERE id = $1 AND household_id = $2
)
`

type MembershipBelongsToHouseholdParams struct {
	ID          pgtype.UUID
	HouseholdID pgtype.UUID
}

// MembershipBelongsToHousehold answers whether a membership is in this
// household, so an account can never be assigned to a member of another one.
func (q *Queries) MembershipBelongsToHousehold(ctx context.Context, arg MembershipBelongsToHouseholdParams) (bool, error) {
	row := q.db.QueryRow(ctx, membershipBelongsToHousehold, arg.ID, arg.HouseholdID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setAccountArchived = `-- name: SetAccountArchived :one
UPDATE accounts
SET archived_at = $3
WHERE household_id = $1 AND id = $2
RETURNING id, household_id, nickname, type, owner_membership_id, opening_balance_minor, opening_balance_currency, opening_balance_as_of, count_toward_net_worth, visible_to_limited_members, archived_at, created_at
`

type SetAccountArchivedParams struct {
	HouseholdID pgtype.UUID
	ID          pgtype.UUID
	ArchivedAt  pgtype.Timestamptz
}

// SetAccountArchived stamps or clears archived_at. There is no DELETE query
// in this file: transactions reference these rows, and deleting an account
// would erase their history along with it.
func (q *Queries) SetAccountArchived(ctx context.Context, arg SetAccountArchivedParams) (Account, error) {
	row := q.db.QueryRow(ctx, setAccountArchived, arg.HouseholdID, arg.ID, arg.ArchivedAt)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Nickname,
		&i.Type,
		&i.OwnerMembershipID,
		&i.OpeningBalanceMinor,
		&i.OpeningBalanceCurrency,
		&i.OpeningBalanceAsOf,
		&i.CountTowardNetWorth,
		&i.VisibleToLimitedMembers,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET nickname                   = $3,
    type                       = $4,
    owner_membership_id        = $5,
    opening_balance_minor      = $6,
    opening_balance_currency   = $7,
    opening_balance_as_of      = $8,
    count_toward_net_worth     = $9,
    visible_to_limited_members = $10
WHERE household_id = $1 AND id = $2
RETURNING id, household_id, nickname, type, owner_membership_id, opening_balance_minor, opening_balance_currency, opening_balance_as_of, count_toward_net_worth, visible_to_limited_members, archived_at, created_at
`

type UpdateAccountParams struct {
	HouseholdID             pgtype.UUID
	ID                      pgtype.UUID
	Nickname                string
	Type                    string
	OwnerMembershipID       pgtype.UUID
	OpeningBalanceMinor     int64
	OpeningBalanceCurrency  string
	OpeningBalanceAsOf      pgtype.Date
	CountTowardNetWorth     bool
	VisibleToLimitedMembers bool
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.HouseholdID,
		arg.ID,
		arg.Nickname,
		arg.Type,
		arg.OwnerMembershipID,
		arg.OpeningBalanceMinor,
		arg.OpeningBalanceCurrency,
		arg.OpeningBalanceAsOf,
		arg.CountTowardNetWorth,
		arg.VisibleToLimitedMembers,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Nickname,
		&i.Type,
		&i.OwnerMembershipID,
		&i.OpeningBalanceMinor,
		&i.OpeningBalanceCurrency,
		&i.OpeningBalanceAsOf,
		&i.CountTowardNetWorth,
		&i.VisibleToLimitedMembers,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}
