// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_directory.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveHouseholdsSince = `-- name: CountActiveHouseholdsSince :one
SELECT COUNT(*) FROM households h
WHERE EXISTS (
    SELECT 1 FROM sessions s
    WHERE s.household_id = h.id
      AND COALESCE(s.last_seen_at, s.created_at) >= $1
)
`

func (q *Queries) CountActiveHouseholdsSince(ctx context.Context, lastSeenAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveHouseholdsSince, lastSeenAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countHouseholds = `-- name: CountHouseholds :one

SELECT COUNT(*) FROM households
`

// The operator's read-only view across every household. Nothing here
// writes. "When was this session last used" is COALESCE(last_seen_at,
// created_at) -- a session from before migration 00013, or one never
// touched, counts from its creation -- and that expression appears only in
// this file so it cannot drift.
func (q *Queries) CountHouseholds(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countHouseholds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingInvites = `-- name: CountPendingInvites :one
SELECT COUNT(*) FROM invites WHERE accepted_at IS NULL AND expires_at > $1
`

func (q *Queries) CountPendingInvites(ctx context.Context, expiresAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingInvites, expiresAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSignupsSinceForAdmin = `-- name: CountSignupsSinceForAdmin :one
SELECT
    COUNT(*)::bigint AS requested,
    COUNT(*) FILTER (WHERE consumed_at IS NOT NULL)::bigint AS completed
FROM signups
WHERE created_at >= $1
`

type CountSignupsSinceForAdminRow struct {
	Requested int64
	Completed int64
}

// Named ...ForAdmin (unlike the other Count* queries here) because
// queries/signup.sql already has a CountSignupsSince -- a single-column
// count used for per-address rate limiting -- and sqlc rejects a duplicate
// query name across files even though the shapes differ.
// Both channels: the table's own CHECK guarantees exactly one of email or
// telegram_chat_id is set, so a plain count is a count of sign-ups.
func (q *Queries) CountSignupsSinceForAdmin(ctx context.Context, createdAt pgtype.Timestamptz) (CountSignupsSinceForAdminRow, error) {
	row := q.db.QueryRow(ctx, countSignupsSinceForAdmin, createdAt)
	var i CountSignupsSinceForAdminRow
	err := row.Scan(&i.Requested, &i.Completed)
	return i, err
}

const getHouseholdForAdmin = `-- name: GetHouseholdForAdmin :one
SELECT id, name, family_name, primary_currency, created_at
FROM households WHERE id = $1
`

type GetHouseholdForAdminRow struct {
	ID              pgtype.UUID
	Name            string
	FamilyName      string
	PrimaryCurrency string
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) GetHouseholdForAdmin(ctx context.Context, id pgtype.UUID) (GetHouseholdForAdminRow, error) {
	row := q.db.QueryRow(ctx, getHouseholdForAdmin, id)
	var i GetHouseholdForAdminRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FamilyName,
		&i.PrimaryCurrency,
		&i.CreatedAt,
	)
	return i, err
}

const listMembersForAdmin = `-- name: ListMembersForAdmin :many
SELECT
    u.id AS user_id,
    u.display_name,
    u.email,
    m.role,
    m.capabilities,
    (ta.user_id IS NOT NULL)::boolean AS has_telegram,
    (SELECT MAX(COALESCE(s.last_seen_at, s.created_at)) FROM sessions s
       WHERE s.user_id = u.id AND s.household_id = m.household_id)::timestamptz AS last_active_at
FROM memberships m
JOIN users u ON u.id = m.user_id
LEFT JOIN telegram_accounts ta ON ta.user_id = u.id
WHERE m.household_id = $1
ORDER BY m.joined_at
`

type ListMembersForAdminRow struct {
	UserID       pgtype.UUID
	DisplayName  string
	Email        *string
	Role         string
	Capabilities []string
	HasTelegram  bool
	LastActiveAt pgtype.Timestamptz
}

// has_telegram comes from the join, never from email IS NULL: a user with
// neither is a defect the screen should surface, not a state it names.
func (q *Queries) ListMembersForAdmin(ctx context.Context, householdID pgtype.UUID) ([]ListMembersForAdminRow, error) {
	rows, err := q.db.Query(ctx, listMembersForAdmin, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersForAdminRow
	for rows.Next() {
		var i ListMembersForAdminRow
		if err := rows.Scan(
			&i.UserID,
			&i.DisplayName,
			&i.Email,
			&i.Role,
			&i.Capabilities,
			&i.HasTelegram,
			&i.LastActiveAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInvitesForAdmin = `-- name: ListPendingInvitesForAdmin :many
SELECT i.name, i.email, i.role, i.expires_at, inviter.display_name AS invited_by_name
FROM invites i
JOIN users inviter ON inviter.id = i.invited_by
WHERE i.household_id = $1 AND i.accepted_at IS NULL AND i.expires_at > $2
ORDER BY i.created_at
`

type ListPendingInvitesForAdminParams struct {
	HouseholdID pgtype.UUID
	ExpiresAt   pgtype.Timestamptz
}

type ListPendingInvitesForAdminRow struct {
	Name          string
	Email         string
	Role          string
	ExpiresAt     pgtype.Timestamptz
	InvitedByName string
}

func (q *Queries) ListPendingInvitesForAdmin(ctx context.Context, arg ListPendingInvitesForAdminParams) ([]ListPendingInvitesForAdminRow, error) {
	rows, err := q.db.Query(ctx, listPendingInvitesForAdmin, arg.HouseholdID, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingInvitesForAdminRow
	for rows.Next() {
		var i ListPendingInvitesForAdminRow
		if err := rows.Scan(
			&i.Name,
			&i.Email,
			&i.Role,
			&i.ExpiresAt,
			&i.InvitedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchHouseholds = `-- name: SearchHouseholds :many
SELECT
    h.id,
    h.name,
    h.family_name,
    h.primary_currency,
    h.created_at,
    (SELECT COUNT(*) FROM memberships m WHERE m.household_id = h.id)::bigint AS member_count,
    (SELECT MAX(COALESCE(s.last_seen_at, s.created_at)) FROM sessions s
       WHERE s.household_id = h.id)::timestamptz AS last_active_at,
    ($1::boolean
       AND (h.name ILIKE $2 OR h.family_name ILIKE $2))::boolean AS household_matched,
    mu.display_name AS match_name,
    mu.email AS match_email
FROM households h
LEFT JOIN LATERAL (
    SELECT m.user_id
    FROM memberships m
    JOIN users u ON u.id = m.user_id
    WHERE $1::boolean
      AND m.household_id = h.id
      AND (u.display_name ILIKE $2 OR u.email ILIKE $2)
    ORDER BY m.joined_at
    LIMIT 1
) mm ON true
LEFT JOIN users mu ON mu.id = mm.user_id
WHERE NOT $1::boolean
   OR h.name ILIKE $2
   OR h.family_name ILIKE $2
   OR mm.user_id IS NOT NULL
ORDER BY last_active_at DESC NULLS LAST, h.created_at DESC
LIMIT $3::int
`

type SearchHouseholdsParams struct {
	HasQuery bool
	Pattern  string
	RowLimit int32
}

type SearchHouseholdsRow struct {
	ID               pgtype.UUID
	Name             string
	FamilyName       string
	PrimaryCurrency  string
	CreatedAt        pgtype.Timestamptz
	MemberCount      int64
	LastActiveAt     pgtype.Timestamptz
	HouseholdMatched bool
	MatchName        *string
	MatchEmail       *string
}

// pattern is the caller-escaped '%q%' (see likePattern in the repo);
// has_query is false for an empty search, which must return every
// household and name no matched member. The first LATERAL join finds the
// id of the first member (by joined_at) whose name or email matched, so a
// row can say why it appeared when the household itself did not match --
// its id alone is selected there, never its display_name/email, because
// sqlc's nullability analysis for a LEFT JOIN onto a derived subquery
// (LATERAL or not -- sqlc-dev/sqlc#3667) does not mark a NOT NULL source
// column nullable, and a match_name generated as plain string then fails at
// scan time with "cannot scan NULL into *string" on every row with no
// match. The second, plain `LEFT JOIN users mu` fetches that member's name
// and email; a LEFT JOIN straight onto a real table is the pattern
// GetTransaction's paid_by_name already relies on and sqlc infers correctly.
func (q *Queries) SearchHouseholds(ctx context.Context, arg SearchHouseholdsParams) ([]SearchHouseholdsRow, error) {
	rows, err := q.db.Query(ctx, searchHouseholds, arg.HasQuery, arg.Pattern, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchHouseholdsRow
	for rows.Next() {
		var i SearchHouseholdsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FamilyName,
			&i.PrimaryCurrency,
			&i.CreatedAt,
			&i.MemberCount,
			&i.LastActiveAt,
			&i.HouseholdMatched,
			&i.MatchName,
			&i.MatchEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
