// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminReauthFailuresSince = `-- name: AdminReauthFailuresSince :many
SELECT at FROM admin_reauth_attempts
WHERE user_id = $1 AND succeeded = false AND at >= $2
ORDER BY at
`

type AdminReauthFailuresSinceParams struct {
	UserID pgtype.UUID
	At     pgtype.Timestamptz
}

func (q *Queries) AdminReauthFailuresSince(ctx context.Context, arg AdminReauthFailuresSinceParams) ([]pgtype.Timestamptz, error) {
	rows, err := q.db.Query(ctx, adminReauthFailuresSince, arg.UserID, arg.At)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Timestamptz
	for rows.Next() {
		var at pgtype.Timestamptz
		if err := rows.Scan(&at); err != nil {
			return nil, err
		}
		items = append(items, at)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearAdminReauthFailures = `-- name: ClearAdminReauthFailures :exec
DELETE FROM admin_reauth_attempts WHERE user_id = $1
`

func (q *Queries) ClearAdminReauthFailures(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearAdminReauthFailures, userID)
	return err
}

const clearHouseholdFlag = `-- name: ClearHouseholdFlag :exec
DELETE FROM household_feature_flags WHERE household_id = $1 AND key = $2
`

type ClearHouseholdFlagParams struct {
	HouseholdID pgtype.UUID
	Key         string
}

func (q *Queries) ClearHouseholdFlag(ctx context.Context, arg ClearHouseholdFlagParams) error {
	_, err := q.db.Exec(ctx, clearHouseholdFlag, arg.HouseholdID, arg.Key)
	return err
}

const getGlobalFlagOverrides = `-- name: GetGlobalFlagOverrides :many
SELECT key, enabled FROM feature_flags
`

type GetGlobalFlagOverridesRow struct {
	Key     string
	Enabled bool
}

func (q *Queries) GetGlobalFlagOverrides(ctx context.Context) ([]GetGlobalFlagOverridesRow, error) {
	rows, err := q.db.Query(ctx, getGlobalFlagOverrides)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGlobalFlagOverridesRow
	for rows.Next() {
		var i GetGlobalFlagOverridesRow
		if err := rows.Scan(&i.Key, &i.Enabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHouseholdFlagOverrides = `-- name: GetHouseholdFlagOverrides :many
SELECT key, enabled FROM household_feature_flags WHERE household_id = $1
`

type GetHouseholdFlagOverridesRow struct {
	Key     string
	Enabled bool
}

func (q *Queries) GetHouseholdFlagOverrides(ctx context.Context, householdID pgtype.UUID) ([]GetHouseholdFlagOverridesRow, error) {
	rows, err := q.db.Query(ctx, getHouseholdFlagOverrides, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHouseholdFlagOverridesRow
	for rows.Next() {
		var i GetHouseholdFlagOverridesRow
		if err := rows.Scan(&i.Key, &i.Enabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlatformAdmin = `-- name: GetPlatformAdmin :one
SELECT user_id, note, created_at FROM platform_admins WHERE user_id = $1
`

func (q *Queries) GetPlatformAdmin(ctx context.Context, userID pgtype.UUID) (PlatformAdmin, error) {
	row := q.db.QueryRow(ctx, getPlatformAdmin, userID)
	var i PlatformAdmin
	err := row.Scan(&i.UserID, &i.Note, &i.CreatedAt)
	return i, err
}

const grantPlatformAdmin = `-- name: GrantPlatformAdmin :exec
INSERT INTO platform_admins (user_id, note) VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET note = EXCLUDED.note
`

type GrantPlatformAdminParams struct {
	UserID pgtype.UUID
	Note   string
}

func (q *Queries) GrantPlatformAdmin(ctx context.Context, arg GrantPlatformAdminParams) error {
	_, err := q.db.Exec(ctx, grantPlatformAdmin, arg.UserID, arg.Note)
	return err
}

const listHouseholdFlagOverrides = `-- name: ListHouseholdFlagOverrides :many
SELECT hff.household_id, h.name AS household_name, hff.key, hff.enabled
FROM household_feature_flags hff
JOIN households h ON h.id = hff.household_id
ORDER BY h.name, hff.key
`

type ListHouseholdFlagOverridesRow struct {
	HouseholdID   pgtype.UUID
	HouseholdName string
	Key           string
	Enabled       bool
}

func (q *Queries) ListHouseholdFlagOverrides(ctx context.Context) ([]ListHouseholdFlagOverridesRow, error) {
	rows, err := q.db.Query(ctx, listHouseholdFlagOverrides)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHouseholdFlagOverridesRow
	for rows.Next() {
		var i ListHouseholdFlagOverridesRow
		if err := rows.Scan(
			&i.HouseholdID,
			&i.HouseholdName,
			&i.Key,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformAdmins = `-- name: ListPlatformAdmins :many
SELECT pa.user_id, u.email, u.display_name, pa.note, pa.created_at
FROM platform_admins pa
JOIN users u ON u.id = pa.user_id
ORDER BY pa.created_at
`

type ListPlatformAdminsRow struct {
	UserID      pgtype.UUID
	Email       *string
	DisplayName string
	Note        string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListPlatformAdmins(ctx context.Context) ([]ListPlatformAdminsRow, error) {
	rows, err := q.db.Query(ctx, listPlatformAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlatformAdminsRow
	for rows.Next() {
		var i ListPlatformAdminsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.DisplayName,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentAdminAudit = `-- name: RecentAdminAudit :many
SELECT actor_user_id, action, target, detail, ip, created_at
FROM admin_audit_log ORDER BY created_at DESC LIMIT $1
`

type RecentAdminAuditRow struct {
	ActorUserID pgtype.UUID
	Action      string
	Target      string
	Detail      []byte
	Ip          string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) RecentAdminAudit(ctx context.Context, limit int32) ([]RecentAdminAuditRow, error) {
	rows, err := q.db.Query(ctx, recentAdminAudit, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecentAdminAuditRow
	for rows.Next() {
		var i RecentAdminAuditRow
		if err := rows.Scan(
			&i.ActorUserID,
			&i.Action,
			&i.Target,
			&i.Detail,
			&i.Ip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAdminAudit = `-- name: RecordAdminAudit :exec
INSERT INTO admin_audit_log (actor_user_id, action, target, detail, ip, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type RecordAdminAuditParams struct {
	ActorUserID pgtype.UUID
	Action      string
	Target      string
	Detail      []byte
	Ip          string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) RecordAdminAudit(ctx context.Context, arg RecordAdminAuditParams) error {
	_, err := q.db.Exec(ctx, recordAdminAudit,
		arg.ActorUserID,
		arg.Action,
		arg.Target,
		arg.Detail,
		arg.Ip,
		arg.CreatedAt,
	)
	return err
}

const recordAdminReauthAttempt = `-- name: RecordAdminReauthAttempt :exec
INSERT INTO admin_reauth_attempts (user_id, succeeded, at) VALUES ($1, $2, $3)
`

type RecordAdminReauthAttemptParams struct {
	UserID    pgtype.UUID
	Succeeded bool
	At        pgtype.Timestamptz
}

func (q *Queries) RecordAdminReauthAttempt(ctx context.Context, arg RecordAdminReauthAttemptParams) error {
	_, err := q.db.Exec(ctx, recordAdminReauthAttempt, arg.UserID, arg.Succeeded, arg.At)
	return err
}

const revokePlatformAdmin = `-- name: RevokePlatformAdmin :exec
DELETE FROM platform_admins WHERE user_id = $1
`

func (q *Queries) RevokePlatformAdmin(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokePlatformAdmin, userID)
	return err
}

const setGlobalFlag = `-- name: SetGlobalFlag :exec
INSERT INTO feature_flags (key, enabled, updated_by) VALUES ($1, $2, $3)
ON CONFLICT (key) DO UPDATE
  SET enabled = EXCLUDED.enabled, updated_at = now(), updated_by = EXCLUDED.updated_by
`

type SetGlobalFlagParams struct {
	Key       string
	Enabled   bool
	UpdatedBy pgtype.UUID
}

func (q *Queries) SetGlobalFlag(ctx context.Context, arg SetGlobalFlagParams) error {
	_, err := q.db.Exec(ctx, setGlobalFlag, arg.Key, arg.Enabled, arg.UpdatedBy)
	return err
}

const setHouseholdFlag = `-- name: SetHouseholdFlag :exec
INSERT INTO household_feature_flags (household_id, key, enabled, updated_by) VALUES ($1, $2, $3, $4)
ON CONFLICT (household_id, key) DO UPDATE
  SET enabled = EXCLUDED.enabled, updated_at = now(), updated_by = EXCLUDED.updated_by
`

type SetHouseholdFlagParams struct {
	HouseholdID pgtype.UUID
	Key         string
	Enabled     bool
	UpdatedBy   pgtype.UUID
}

func (q *Queries) SetHouseholdFlag(ctx context.Context, arg SetHouseholdFlagParams) error {
	_, err := q.db.Exec(ctx, setHouseholdFlag,
		arg.HouseholdID,
		arg.Key,
		arg.Enabled,
		arg.UpdatedBy,
	)
	return err
}
