// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agreements.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgreementSection = `-- name: CreateAgreementSection :one
INSERT INTO agreement_sections (household_id, name, created_at) VALUES ($1, $2, $3)
RETURNING id, name, created_at
`

type CreateAgreementSectionParams struct {
	HouseholdID pgtype.UUID
	Name        string
	CreatedAt   pgtype.Timestamptz
}

type CreateAgreementSectionRow struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

// No ON CONFLICT here: the unique index decides a name collision and
// translate maps it by constraint name (decision 19). A "does this name
// exist" pre-read is a check-then-write two owners can both pass.
func (q *Queries) CreateAgreementSection(ctx context.Context, arg CreateAgreementSectionParams) (CreateAgreementSectionRow, error) {
	row := q.db.QueryRow(ctx, createAgreementSection, arg.HouseholdID, arg.Name, arg.CreatedAt)
	var i CreateAgreementSectionRow
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createAgreementSectionIfAbsent = `-- name: CreateAgreementSectionIfAbsent :exec
INSERT INTO agreement_sections (household_id, name, created_at) VALUES ($1, $2, $3)
ON CONFLICT (household_id, name) DO NOTHING
`

type CreateAgreementSectionIfAbsentParams struct {
	HouseholdID pgtype.UUID
	Name        string
	CreatedAt   pgtype.Timestamptz
}

// The starter set's insert (decision 17): DO NOTHING, so a second click is a
// no-op rather than a 409.
func (q *Queries) CreateAgreementSectionIfAbsent(ctx context.Context, arg CreateAgreementSectionIfAbsentParams) error {
	_, err := q.db.Exec(ctx, createAgreementSectionIfAbsent, arg.HouseholdID, arg.Name, arg.CreatedAt)
	return err
}

const getAgreementProposal = `-- name: GetAgreementProposal :one
SELECT p.id, p.household_id, p.kind, p.status, p.section_id, p.target_agreement_id, p.body, p.previous_body, p.note, p.park_note, p.proposed_by_membership_id, p.created_at, p.resolved_at,
       COALESCE(array_agg(s.membership_id ORDER BY s.signed_at, s.membership_id)
                FILTER (WHERE s.membership_id IS NOT NULL), '{}')::uuid[] AS signed_by
FROM agreement_proposals p
LEFT JOIN agreement_signatures s ON s.proposal_id = p.id
WHERE p.household_id = $1 AND p.id = $2
GROUP BY p.id
`

type GetAgreementProposalParams struct {
	HouseholdID pgtype.UUID
	ID          pgtype.UUID
}

type GetAgreementProposalRow struct {
	ID                     pgtype.UUID
	HouseholdID            pgtype.UUID
	Kind                   string
	Status                 string
	SectionID              pgtype.UUID
	TargetAgreementID      pgtype.UUID
	Body                   string
	PreviousBody           string
	Note                   string
	ParkNote               string
	ProposedByMembershipID pgtype.UUID
	CreatedAt              pgtype.Timestamptz
	ResolvedAt             pgtype.Timestamptz
	SignedBy               []pgtype.UUID
}

// One proposal whatever its status, withdrawn included: the withdraw
// handler's proposer check costs one query rather than a composed document.
func (q *Queries) GetAgreementProposal(ctx context.Context, arg GetAgreementProposalParams) (GetAgreementProposalRow, error) {
	row := q.db.QueryRow(ctx, getAgreementProposal, arg.HouseholdID, arg.ID)
	var i GetAgreementProposalRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Kind,
		&i.Status,
		&i.SectionID,
		&i.TargetAgreementID,
		&i.Body,
		&i.PreviousBody,
		&i.Note,
		&i.ParkNote,
		&i.ProposedByMembershipID,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.SignedBy,
	)
	return i, err
}

const listAcceptedAgreementProposals = `-- name: ListAcceptedAgreementProposals :many
SELECT p.id, p.household_id, p.kind, p.status, p.section_id, p.target_agreement_id, p.body, p.previous_body, p.note, p.park_note, p.proposed_by_membership_id, p.created_at, p.resolved_at,
       COALESCE(array_agg(s.membership_id ORDER BY s.signed_at, s.membership_id)
                FILTER (WHERE s.membership_id IS NOT NULL), '{}')::uuid[] AS signed_by
FROM agreement_proposals p
LEFT JOIN agreement_signatures s ON s.proposal_id = p.id
WHERE p.household_id = $1 AND p.status = 'accepted'
GROUP BY p.id ORDER BY p.resolved_at, p.id
`

type ListAcceptedAgreementProposalsRow struct {
	ID                     pgtype.UUID
	HouseholdID            pgtype.UUID
	Kind                   string
	Status                 string
	SectionID              pgtype.UUID
	TargetAgreementID      pgtype.UUID
	Body                   string
	PreviousBody           string
	Note                   string
	ParkNote               string
	ProposedByMembershipID pgtype.UUID
	CreatedAt              pgtype.Timestamptz
	ResolvedAt             pgtype.Timestamptz
	SignedBy               []pgtype.UUID
}

func (q *Queries) ListAcceptedAgreementProposals(ctx context.Context, householdID pgtype.UUID) ([]ListAcceptedAgreementProposalsRow, error) {
	rows, err := q.db.Query(ctx, listAcceptedAgreementProposals, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAcceptedAgreementProposalsRow
	for rows.Next() {
		var i ListAcceptedAgreementProposalsRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Kind,
			&i.Status,
			&i.SectionID,
			&i.TargetAgreementID,
			&i.Body,
			&i.PreviousBody,
			&i.Note,
			&i.ParkNote,
			&i.ProposedByMembershipID,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.SignedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgreementSections = `-- name: ListAgreementSections :many

SELECT id, name, created_at FROM agreement_sections
WHERE household_id = $1 ORDER BY created_at, id
`

type ListAgreementSectionsRow struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

// Ordering is created_at, id everywhere (decision 11: no position column, so
// insertion order IS the order). The one exception is
// ListAcceptedAgreementProposals: a version is the k-th ACCEPTANCE, and two
// proposals created A then B can be accepted B then A.
func (q *Queries) ListAgreementSections(ctx context.Context, householdID pgtype.UUID) ([]ListAgreementSectionsRow, error) {
	rows, err := q.db.Query(ctx, listAgreementSections, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgreementSectionsRow
	for rows.Next() {
		var i ListAgreementSectionsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgreementSectionsNamed = `-- name: ListAgreementSectionsNamed :many
SELECT id, name, created_at FROM agreement_sections
WHERE household_id = $1 AND name = ANY($2::text[])
ORDER BY created_at, id
`

type ListAgreementSectionsNamedParams struct {
	HouseholdID pgtype.UUID
	Names       []string
}

type ListAgreementSectionsNamedRow struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

// The starter set's read-back, run inside the same transaction: it is how the
// caller proves all four landed rather than two of four.
func (q *Queries) ListAgreementSectionsNamed(ctx context.Context, arg ListAgreementSectionsNamedParams) ([]ListAgreementSectionsNamedRow, error) {
	rows, err := q.db.Query(ctx, listAgreementSectionsNamed, arg.HouseholdID, arg.Names)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgreementSectionsNamedRow
	for rows.Next() {
		var i ListAgreementSectionsNamedRow
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveAgreements = `-- name: ListLiveAgreements :many
SELECT id, section_id, body, added_by_proposal_id, created_at FROM agreements
WHERE household_id = $1 AND removed_at IS NULL ORDER BY created_at, id
`

type ListLiveAgreementsRow struct {
	ID                pgtype.UUID
	SectionID         pgtype.UUID
	Body              string
	AddedByProposalID pgtype.UUID
	CreatedAt         pgtype.Timestamptz
}

// Live rows only. The predicate is here rather than in Go so a growing tail
// of removed rows is never fetched to be filtered away, and it matches
// agreements_household_live_idx.
func (q *Queries) ListLiveAgreements(ctx context.Context, householdID pgtype.UUID) ([]ListLiveAgreementsRow, error) {
	rows, err := q.db.Query(ctx, listLiveAgreements, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiveAgreementsRow
	for rows.Next() {
		var i ListLiveAgreementsRow
		if err := rows.Scan(
			&i.ID,
			&i.SectionID,
			&i.Body,
			&i.AddedByProposalID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenAgreementProposals = `-- name: ListOpenAgreementProposals :many
SELECT p.id, p.household_id, p.kind, p.status, p.section_id, p.target_agreement_id, p.body, p.previous_body, p.note, p.park_note, p.proposed_by_membership_id, p.created_at, p.resolved_at,
       COALESCE(array_agg(s.membership_id ORDER BY s.signed_at, s.membership_id)
                FILTER (WHERE s.membership_id IS NOT NULL), '{}')::uuid[] AS signed_by
FROM agreement_proposals p
LEFT JOIN agreement_signatures s ON s.proposal_id = p.id
WHERE p.household_id = $1 AND p.status IN ('pending', 'parked')
GROUP BY p.id ORDER BY p.created_at, p.id
`

type ListOpenAgreementProposalsRow struct {
	ID                     pgtype.UUID
	HouseholdID            pgtype.UUID
	Kind                   string
	Status                 string
	SectionID              pgtype.UUID
	TargetAgreementID      pgtype.UUID
	Body                   string
	PreviousBody           string
	Note                   string
	ParkNote               string
	ProposedByMembershipID pgtype.UUID
	CreatedAt              pgtype.Timestamptz
	ResolvedAt             pgtype.Timestamptz
	SignedBy               []pgtype.UUID
}

// The three proposal reads select p.* plus the same signed_by aggregate, so
// sqlc generates three structs with identical fields in identical order --
// which is what makes toAgreementProposal's conversion at each call site
// legal. Change one select list and the conversion stops compiling: that is
// the warning, not an accident.
//
// GROUP BY p.id is enough because id is the primary key (Postgres then treats
// every other column of p as functionally dependent), the same rule
// ListRetroActions documents. The FILTER clause is what keeps an unsigned
// proposal at '{}' rather than array_agg's default one-element array holding
// a single NULL, and the ORDER BY inside array_agg makes the signature list
// stable between reads.
func (q *Queries) ListOpenAgreementProposals(ctx context.Context, householdID pgtype.UUID) ([]ListOpenAgreementProposalsRow, error) {
	rows, err := q.db.Query(ctx, listOpenAgreementProposals, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenAgreementProposalsRow
	for rows.Next() {
		var i ListOpenAgreementProposalsRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Kind,
			&i.Status,
			&i.SectionID,
			&i.TargetAgreementID,
			&i.Body,
			&i.PreviousBody,
			&i.Note,
			&i.ParkNote,
			&i.ProposedByMembershipID,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.SignedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
