// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_token.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (user_id, household_id, name, token_hash, prefix, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, household_id, name, token_hash, prefix, created_at, expires_at, last_used_at, revoked_at
`

type CreateAPITokenParams struct {
	UserID      pgtype.UUID
	HouseholdID pgtype.UUID
	Name        string
	TokenHash   []byte
	Prefix      string
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.UserID,
		arg.HouseholdID,
		arg.Name,
		arg.TokenHash,
		arg.Prefix,
		arg.ExpiresAt,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.HouseholdID,
		&i.Name,
		&i.TokenHash,
		&i.Prefix,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getLiveAPIToken = `-- name: GetLiveAPIToken :one
SELECT id, user_id, household_id, name, token_hash, prefix, created_at, expires_at, last_used_at, revoked_at FROM api_tokens
WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > now()
`

// The live lookup: revoked or expired is unfindable, the same shape as
// GetLiveSession, so no caller ever holds a dead token and forgets to check.
func (q *Queries) GetLiveAPIToken(ctx context.Context, tokenHash []byte) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getLiveAPIToken, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.HouseholdID,
		&i.Name,
		&i.TokenHash,
		&i.Prefix,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAPITokensForUser = `-- name: ListAPITokensForUser :many
SELECT id, user_id, household_id, name, token_hash, prefix, created_at, expires_at, last_used_at, revoked_at FROM api_tokens
WHERE user_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListAPITokensForUser(ctx context.Context, userID pgtype.UUID) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, listAPITokensForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiToken
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.HouseholdID,
			&i.Name,
			&i.TokenHash,
			&i.Prefix,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIToken = `-- name: RevokeAPIToken :execrows
UPDATE api_tokens SET revoked_at = now()
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeAPITokenParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

// User-scoped on purpose: revoking by id alone would let one member revoke
// another's token by guessing. A miss (wrong user, already revoked) affects
// no row and the repository turns that into ErrNotFound.
func (q *Queries) RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIToken, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAPITokensForUser = `-- name: RevokeAPITokensForUser :exec
UPDATE api_tokens SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAPITokensForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAPITokensForUser, userID)
	return err
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens SET last_used_at = $2 WHERE id = $1
`

type TouchAPITokenParams struct {
	ID         pgtype.UUID
	LastUsedAt pgtype.Timestamptz
}

func (q *Queries) TouchAPIToken(ctx context.Context, arg TouchAPITokenParams) error {
	_, err := q.db.Exec(ctx, touchAPIToken, arg.ID, arg.LastUsedAt)
	return err
}
