// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bill.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const billMonthDueTotals = `-- name: BillMonthDueTotals :many
SELECT a.opening_balance_currency AS currency, SUM(p.amount_minor)::bigint AS minor
FROM bill_payments p
JOIN bills b    ON b.id = p.bill_id
JOIN accounts a ON a.id = b.pay_from_account_id
WHERE p.household_id = $1
  AND p.due_on >= $2::date
  AND p.due_on <  $3::date
GROUP BY a.opening_balance_currency
`

type BillMonthDueTotalsParams struct {
	HouseholdID pgtype.UUID
	MonthStart  pgtype.Date
	NextMonth   pgtype.Date
}

type BillMonthDueTotalsRow struct {
	Currency string
	Minor    int64
}

// BillMonthDueTotals is half of the union BillRepository.MonthTotals' own doc
// comment demands. A bill paid this month has already advanced past it (its
// next_due now reads next month), so the two halves come from different
// tables and neither alone is the figure.
//
// No archived_at filter here, unlike BillMonthUnpaidTotals below, and that
// asymmetry is deliberate: this money already left the household, so
// archiving the bill afterwards must not retroactively empty the month it was
// paid in.
func (q *Queries) BillMonthDueTotals(ctx context.Context, arg BillMonthDueTotalsParams) ([]BillMonthDueTotalsRow, error) {
	rows, err := q.db.Query(ctx, billMonthDueTotals, arg.HouseholdID, arg.MonthStart, arg.NextMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillMonthDueTotalsRow
	for rows.Next() {
		var i BillMonthDueTotalsRow
		if err := rows.Scan(&i.Currency, &i.Minor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const billMonthUnpaidTotals = `-- name: BillMonthUnpaidTotals :many
SELECT a.opening_balance_currency AS currency, SUM(b.amount_minor)::bigint AS minor
FROM bills b
JOIN accounts a ON a.id = b.pay_from_account_id
WHERE b.household_id = $1
  AND b.archived_at IS NULL
  AND b.next_due >= $2::date
  AND b.next_due <  $3::date
GROUP BY a.opening_balance_currency
`

type BillMonthUnpaidTotalsParams struct {
	HouseholdID pgtype.UUID
	MonthStart  pgtype.Date
	NextMonth   pgtype.Date
}

type BillMonthUnpaidTotalsRow struct {
	Currency string
	Minor    int64
}

// BillMonthUnpaidTotals is the other half of the union: bills still due this
// month that have not been paid yet. archived_at IS NULL here, unlike
// BillMonthDueTotals above -- a bill nobody intends to pay again is not an
// obligation, so an archived bill must not inflate what is still owed.
func (q *Queries) BillMonthUnpaidTotals(ctx context.Context, arg BillMonthUnpaidTotalsParams) ([]BillMonthUnpaidTotalsRow, error) {
	rows, err := q.db.Query(ctx, billMonthUnpaidTotals, arg.HouseholdID, arg.MonthStart, arg.NextMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillMonthUnpaidTotalsRow
	for rows.Next() {
		var i BillMonthUnpaidTotalsRow
		if err := rows.Scan(&i.Currency, &i.Minor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createBill = `-- name: CreateBill :one
WITH created AS (
    INSERT INTO bills (household_id, name, amount_minor, cadence, next_due, due_anchor_day,
                        category_id, pay_from_account_id, paid_by_membership_id, autopay, is_subscription)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
    RETURNING id, household_id, name, amount_minor, cadence, next_due, due_anchor_day,
              category_id, pay_from_account_id, paid_by_membership_id, autopay, is_subscription, archived_at
)
SELECT created.id, created.household_id, created.name, created.amount_minor, created.cadence, created.next_due,
       created.due_anchor_day, created.category_id, created.pay_from_account_id, created.paid_by_membership_id,
       created.autopay, created.is_subscription, created.archived_at,
       COALESCE(c.name, '')  AS category_name,
       a.nickname            AS account_name,
       a.opening_balance_currency AS currency
FROM created
JOIN accounts a ON a.id = created.pay_from_account_id
LEFT JOIN categories c ON c.id = created.category_id
`

type CreateBillParams struct {
	HouseholdID        pgtype.UUID
	Name               string
	AmountMinor        int64
	Cadence            string
	NextDue            pgtype.Date
	DueAnchorDay       int16
	CategoryID         pgtype.UUID
	PayFromAccountID   pgtype.UUID
	PaidByMembershipID pgtype.UUID
	Autopay            bool
	IsSubscription     bool
}

type CreateBillRow struct {
	ID                 pgtype.UUID
	HouseholdID        pgtype.UUID
	Name               string
	AmountMinor        int64
	Cadence            string
	NextDue            pgtype.Date
	DueAnchorDay       int16
	CategoryID         pgtype.UUID
	PayFromAccountID   pgtype.UUID
	PaidByMembershipID pgtype.UUID
	Autopay            bool
	IsSubscription     bool
	ArchivedAt         pgtype.Timestamptz
	CategoryName       string
	AccountName        string
	Currency           string
}

// CreateBill writes one row and joins straight back to it in the same
// statement, via a CTE, rather than a bare RETURNING off the bills table --
// bills has no currency column, so a bare RETURNING has nothing to build
// Bill.Amount.Currency from, and BillRecord requires it populated (see this
// file's header comment on ListBills). A name colliding with UNIQUE
// (household_id, name) -- archived rows included -- surfaces as a 23505 that
// translate maps to domain.ErrBillNameTaken, the same categoryNameUnique/
// goalNameUnique pattern.
func (q *Queries) CreateBill(ctx context.Context, arg CreateBillParams) (CreateBillRow, error) {
	row := q.db.QueryRow(ctx, createBill,
		arg.HouseholdID,
		arg.Name,
		arg.AmountMinor,
		arg.Cadence,
		arg.NextDue,
		arg.DueAnchorDay,
		arg.CategoryID,
		arg.PayFromAccountID,
		arg.PaidByMembershipID,
		arg.Autopay,
		arg.IsSubscription,
	)
	var i CreateBillRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.AmountMinor,
		&i.Cadence,
		&i.NextDue,
		&i.DueAnchorDay,
		&i.CategoryID,
		&i.PayFromAccountID,
		&i.PaidByMembershipID,
		&i.Autopay,
		&i.IsSubscription,
		&i.ArchivedAt,
		&i.CategoryName,
		&i.AccountName,
		&i.Currency,
	)
	return i, err
}

const getBill = `-- name: GetBill :one
SELECT b.id, b.household_id, b.name, b.amount_minor, b.cadence, b.next_due,
       b.due_anchor_day, b.category_id, b.pay_from_account_id,
       b.paid_by_membership_id, b.autopay, b.is_subscription, b.archived_at,
       COALESCE(c.name, '')  AS category_name,
       a.nickname            AS account_name,
       a.opening_balance_currency AS currency
FROM bills b
JOIN accounts a ON a.id = b.pay_from_account_id
LEFT JOIN categories c ON c.id = b.category_id
WHERE b.household_id = $1 AND b.id = $2
`

type GetBillParams struct {
	HouseholdID pgtype.UUID
	ID          pgtype.UUID
}

type GetBillRow struct {
	ID                 pgtype.UUID
	HouseholdID        pgtype.UUID
	Name               string
	AmountMinor        int64
	Cadence            string
	NextDue            pgtype.Date
	DueAnchorDay       int16
	CategoryID         pgtype.UUID
	PayFromAccountID   pgtype.UUID
	PaidByMembershipID pgtype.UUID
	Autopay            bool
	IsSubscription     bool
	ArchivedAt         pgtype.Timestamptz
	CategoryName       string
	AccountName        string
	Currency           string
}

// GetBill is ListBills scoped to one bill. household_id AND id are both
// required in the WHERE -- a bill id from another household must match no
// row, so it is indistinguishable from an id that never existed
// (BillRepository.Get's own doc comment).
func (q *Queries) GetBill(ctx context.Context, arg GetBillParams) (GetBillRow, error) {
	row := q.db.QueryRow(ctx, getBill, arg.HouseholdID, arg.ID)
	var i GetBillRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.AmountMinor,
		&i.Cadence,
		&i.NextDue,
		&i.DueAnchorDay,
		&i.CategoryID,
		&i.PayFromAccountID,
		&i.PaidByMembershipID,
		&i.Autopay,
		&i.IsSubscription,
		&i.ArchivedAt,
		&i.CategoryName,
		&i.AccountName,
		&i.Currency,
	)
	return i, err
}

const listBillPaymentsForMonth = `-- name: ListBillPaymentsForMonth :many
SELECT p.id, p.bill_id, p.household_id, p.due_on, p.paid_on, p.amount_minor,
       p.transaction_id, b.name AS bill_name, b.autopay, a.opening_balance_currency AS currency
FROM bill_payments p
JOIN bills b    ON b.id = p.bill_id
JOIN accounts a ON a.id = b.pay_from_account_id
WHERE p.household_id = $1
  AND p.due_on >= $2::date
  AND p.due_on <  $3::date
ORDER BY p.paid_on DESC, b.name
`

type ListBillPaymentsForMonthParams struct {
	HouseholdID pgtype.UUID
	MonthStart  pgtype.Date
	NextMonth   pgtype.Date
}

type ListBillPaymentsForMonthRow struct {
	ID            pgtype.UUID
	BillID        pgtype.UUID
	HouseholdID   pgtype.UUID
	DueOn         pgtype.Date
	PaidOn        pgtype.Date
	AmountMinor   int64
	TransactionID pgtype.UUID
	BillName      string
	Autopay       bool
	Currency      string
}

// ListBillPaymentsForMonth returns one household's payments whose due_on
// falls in the month, newest paid_on first, ties by bill name -- the "Paid
// this month" list's own ordering (BillRepository.ListPayments' doc comment).
// Joined to bills for the display name and autopay flag, and to accounts for
// the currency, the same reason every bill-returning query above joins it.
func (q *Queries) ListBillPaymentsForMonth(ctx context.Context, arg ListBillPaymentsForMonthParams) ([]ListBillPaymentsForMonthRow, error) {
	rows, err := q.db.Query(ctx, listBillPaymentsForMonth, arg.HouseholdID, arg.MonthStart, arg.NextMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBillPaymentsForMonthRow
	for rows.Next() {
		var i ListBillPaymentsForMonthRow
		if err := rows.Scan(
			&i.ID,
			&i.BillID,
			&i.HouseholdID,
			&i.DueOn,
			&i.PaidOn,
			&i.AmountMinor,
			&i.TransactionID,
			&i.BillName,
			&i.Autopay,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBills = `-- name: ListBills :many
SELECT b.id, b.household_id, b.name, b.amount_minor, b.cadence, b.next_due,
       b.due_anchor_day, b.category_id, b.pay_from_account_id,
       b.paid_by_membership_id, b.autopay, b.is_subscription, b.archived_at,
       COALESCE(c.name, '')  AS category_name,
       a.nickname            AS account_name,
       a.opening_balance_currency AS currency
FROM bills b
JOIN accounts a ON a.id = b.pay_from_account_id
LEFT JOIN categories c ON c.id = b.category_id
WHERE b.household_id = $1
  AND ($2::boolean OR b.archived_at IS NULL)
ORDER BY b.next_due NULLS LAST, b.name
`

type ListBillsParams struct {
	HouseholdID     pgtype.UUID
	IncludeArchived bool
}

type ListBillsRow struct {
	ID                 pgtype.UUID
	HouseholdID        pgtype.UUID
	Name               string
	AmountMinor        int64
	Cadence            string
	NextDue            pgtype.Date
	DueAnchorDay       int16
	CategoryID         pgtype.UUID
	PayFromAccountID   pgtype.UUID
	PaidByMembershipID pgtype.UUID
	Autopay            bool
	IsSubscription     bool
	ArchivedAt         pgtype.Timestamptz
	CategoryName       string
	AccountName        string
	Currency           string
}

// ListBills returns one household's bills joined to the names the screen
// displays -- the category (COALESCE'd to ” for uncategorised, the ports.go
// NULL convention) and the pay-from account's nickname and currency. The
// currency join is load-bearing, not decoration: bills carries no currency
// column of its own (00008_bills.sql's own comment), so this is the only
// place Bill.Amount's currency can come from.
//
// include_archived is a UNION, not a filter swap -- BillRepository.List's own
// doc comment: false returns only the live bills, true returns the live ones
// AND the archived ones together, each carrying its own ArchivedAt.
func (q *Queries) ListBills(ctx context.Context, arg ListBillsParams) ([]ListBillsRow, error) {
	rows, err := q.db.Query(ctx, listBills, arg.HouseholdID, arg.IncludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBillsRow
	for rows.Next() {
		var i ListBillsRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Name,
			&i.AmountMinor,
			&i.Cadence,
			&i.NextDue,
			&i.DueAnchorDay,
			&i.CategoryID,
			&i.PayFromAccountID,
			&i.PaidByMembershipID,
			&i.Autopay,
			&i.IsSubscription,
			&i.ArchivedAt,
			&i.CategoryName,
			&i.AccountName,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBillArchived = `-- name: SetBillArchived :one
WITH archived AS (
    UPDATE bills
    SET archived_at = CASE WHEN $1::boolean THEN COALESCE(archived_at, $2::timestamptz) ELSE NULL END,
        updated_at = now()
    WHERE bills.household_id = $3 AND bills.id = $4
    RETURNING id, household_id, name, amount_minor, cadence, next_due, due_anchor_day,
              category_id, pay_from_account_id, paid_by_membership_id, autopay, is_subscription, archived_at
)
SELECT archived.id, archived.household_id, archived.name, archived.amount_minor, archived.cadence, archived.next_due,
       archived.due_anchor_day, archived.category_id, archived.pay_from_account_id, archived.paid_by_membership_id,
       archived.autopay, archived.is_subscription, archived.archived_at,
       COALESCE(c.name, '')  AS category_name,
       a.nickname            AS account_name,
       a.opening_balance_currency AS currency
FROM archived
JOIN accounts a ON a.id = archived.pay_from_account_id
LEFT JOIN categories c ON c.id = archived.category_id
`

type SetBillArchivedParams struct {
	Archived    bool
	At          pgtype.Timestamptz
	HouseholdID pgtype.UUID
	ID          pgtype.UUID
}

type SetBillArchivedRow struct {
	ID                 pgtype.UUID
	HouseholdID        pgtype.UUID
	Name               string
	AmountMinor        int64
	Cadence            string
	NextDue            pgtype.Date
	DueAnchorDay       int16
	CategoryID         pgtype.UUID
	PayFromAccountID   pgtype.UUID
	PaidByMembershipID pgtype.UUID
	Autopay            bool
	IsSubscription     bool
	ArchivedAt         pgtype.Timestamptz
	CategoryName       string
	AccountName        string
	Currency           string
}

// SetBillArchived stamps or clears archived_at depending on the caller's
// boolean, scoped the same way UpdateBill is. The COALESCE is "first stamp
// wins": archiving an already-archived bill keeps its original archived_at
// rather than moving it forward to the caller's `at` -- the same
// SetGoalArchived/SetCategoryArchived convention.
func (q *Queries) SetBillArchived(ctx context.Context, arg SetBillArchivedParams) (SetBillArchivedRow, error) {
	row := q.db.QueryRow(ctx, setBillArchived,
		arg.Archived,
		arg.At,
		arg.HouseholdID,
		arg.ID,
	)
	var i SetBillArchivedRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.AmountMinor,
		&i.Cadence,
		&i.NextDue,
		&i.DueAnchorDay,
		&i.CategoryID,
		&i.PayFromAccountID,
		&i.PaidByMembershipID,
		&i.Autopay,
		&i.IsSubscription,
		&i.ArchivedAt,
		&i.CategoryName,
		&i.AccountName,
		&i.Currency,
	)
	return i, err
}

const updateBill = `-- name: UpdateBill :one
WITH updated AS (
    UPDATE bills
    SET name = $3, amount_minor = $4, cadence = $5, next_due = $6, due_anchor_day = $7,
        category_id = $8, pay_from_account_id = $9, paid_by_membership_id = $10,
        autopay = $11, is_subscription = $12, updated_at = now()
    WHERE bills.household_id = $1 AND bills.id = $2
    RETURNING id, household_id, name, amount_minor, cadence, next_due, due_anchor_day,
              category_id, pay_from_account_id, paid_by_membership_id, autopay, is_subscription, archived_at
)
SELECT updated.id, updated.household_id, updated.name, updated.amount_minor, updated.cadence, updated.next_due,
       updated.due_anchor_day, updated.category_id, updated.pay_from_account_id, updated.paid_by_membership_id,
       updated.autopay, updated.is_subscription, updated.archived_at,
       COALESCE(c.name, '')  AS category_name,
       a.nickname            AS account_name,
       a.opening_balance_currency AS currency
FROM updated
JOIN accounts a ON a.id = updated.pay_from_account_id
LEFT JOIN categories c ON c.id = updated.category_id
`

type UpdateBillParams struct {
	HouseholdID        pgtype.UUID
	ID                 pgtype.UUID
	Name               string
	AmountMinor        int64
	Cadence            string
	NextDue            pgtype.Date
	DueAnchorDay       int16
	CategoryID         pgtype.UUID
	PayFromAccountID   pgtype.UUID
	PaidByMembershipID pgtype.UUID
	Autopay            bool
	IsSubscription     bool
}

type UpdateBillRow struct {
	ID                 pgtype.UUID
	HouseholdID        pgtype.UUID
	Name               string
	AmountMinor        int64
	Cadence            string
	NextDue            pgtype.Date
	DueAnchorDay       int16
	CategoryID         pgtype.UUID
	PayFromAccountID   pgtype.UUID
	PaidByMembershipID pgtype.UUID
	Autopay            bool
	IsSubscription     bool
	ArchivedAt         pgtype.Timestamptz
	CategoryName       string
	AccountName        string
	Currency           string
}

// UpdateBill is an unconditional full-row SET -- every mutable column,
// including due_anchor_day, no COALESCE and no dynamic SQL. BillService turns
// a partial PATCH into a complete domain.Bill before this query ever runs
// (ports.go's Update comment), so the anchor arrives already derived and this
// adapter never computes a calendar day. archived_at has no SET clause here,
// the same reason UpdateGoal excludes it: archiving is SetBillArchived's own
// job. Scoped by household_id AND id together, same collision contract as
// CreateBill, same join-via-CTE reason.
func (q *Queries) UpdateBill(ctx context.Context, arg UpdateBillParams) (UpdateBillRow, error) {
	row := q.db.QueryRow(ctx, updateBill,
		arg.HouseholdID,
		arg.ID,
		arg.Name,
		arg.AmountMinor,
		arg.Cadence,
		arg.NextDue,
		arg.DueAnchorDay,
		arg.CategoryID,
		arg.PayFromAccountID,
		arg.PaidByMembershipID,
		arg.Autopay,
		arg.IsSubscription,
	)
	var i UpdateBillRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.AmountMinor,
		&i.Cadence,
		&i.NextDue,
		&i.DueAnchorDay,
		&i.CategoryID,
		&i.PayFromAccountID,
		&i.PaidByMembershipID,
		&i.Autopay,
		&i.IsSubscription,
		&i.ArchivedAt,
		&i.CategoryName,
		&i.AccountName,
		&i.Currency,
	)
	return i, err
}
