// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: budget.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCategoriesInHousehold = `-- name: CountCategoriesInHousehold :one
SELECT count(*) FROM categories
WHERE id = ANY($2::uuid[]) AND household_id = $1
`

type CountCategoriesInHouseholdParams struct {
	HouseholdID pgtype.UUID
	CategoryIds []pgtype.UUID
}

// CountCategoriesInHousehold answers how many of the given category ids
// actually belong to this household. BudgetRepo.Upsert compares this against
// the number of distinct ids it asked about, inside the same transaction as
// the write, and refuses on a mismatch -- the categories table's own FK only
// proves a category exists somewhere, never that it is this household's.
func (q *Queries) CountCategoriesInHousehold(ctx context.Context, arg CountCategoriesInHouseholdParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCategoriesInHousehold, arg.HouseholdID, arg.CategoryIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBudgetLines = `-- name: DeleteBudgetLines :exec
DELETE FROM budget_lines WHERE budget_id = $1
`

func (q *Queries) DeleteBudgetLines(ctx context.Context, budgetID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBudgetLines, budgetID)
	return err
}

const getBudget = `-- name: GetBudget :one
SELECT b.id, b.household_id, b.month, b.expected_income_minor, h.primary_currency
FROM budgets b
JOIN households h ON h.id = b.household_id
WHERE b.household_id = $1 AND b.month = $2
`

type GetBudgetParams struct {
	HouseholdID pgtype.UUID
	Month       pgtype.Date
}

type GetBudgetRow struct {
	ID                  pgtype.UUID
	HouseholdID         pgtype.UUID
	Month               pgtype.Date
	ExpectedIncomeMinor *int64
	PrimaryCurrency     string
}

func (q *Queries) GetBudget(ctx context.Context, arg GetBudgetParams) (GetBudgetRow, error) {
	row := q.db.QueryRow(ctx, getBudget, arg.HouseholdID, arg.Month)
	var i GetBudgetRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Month,
		&i.ExpectedIncomeMinor,
		&i.PrimaryCurrency,
	)
	return i, err
}

const getHouseholdPrimaryCurrency = `-- name: GetHouseholdPrimaryCurrency :one
SELECT primary_currency FROM households WHERE id = $1
`

// GetHouseholdPrimaryCurrency reads the currency budgets.expected_income_minor
// and budget_lines.cap_minor are denominated in -- both columns deliberately
// carry no currency column of their own (migrations/00006_budgets.sql), so a
// Budget's Money is only ever as current as this read.
func (q *Queries) GetHouseholdPrimaryCurrency(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getHouseholdPrimaryCurrency, id)
	var primary_currency string
	err := row.Scan(&primary_currency)
	return primary_currency, err
}

const insertBudgetLine = `-- name: InsertBudgetLine :exec
INSERT INTO budget_lines (budget_id, category_id, cap_minor) VALUES ($1, $2, $3)
`

type InsertBudgetLineParams struct {
	BudgetID   pgtype.UUID
	CategoryID pgtype.UUID
	CapMinor   int64
}

func (q *Queries) InsertBudgetLine(ctx context.Context, arg InsertBudgetLineParams) error {
	_, err := q.db.Exec(ctx, insertBudgetLine, arg.BudgetID, arg.CategoryID, arg.CapMinor)
	return err
}

const listBudgetLines = `-- name: ListBudgetLines :many
SELECT category_id, cap_minor FROM budget_lines WHERE budget_id = $1 ORDER BY category_id
`

type ListBudgetLinesRow struct {
	CategoryID pgtype.UUID
	CapMinor   int64
}

func (q *Queries) ListBudgetLines(ctx context.Context, budgetID pgtype.UUID) ([]ListBudgetLinesRow, error) {
	rows, err := q.db.Query(ctx, listBudgetLines, budgetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBudgetLinesRow
	for rows.Next() {
		var i ListBudgetLinesRow
		if err := rows.Scan(&i.CategoryID, &i.CapMinor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBudgetLinesForBudgets = `-- name: ListBudgetLinesForBudgets :many
SELECT budget_id, category_id, cap_minor FROM budget_lines
WHERE budget_id = ANY($1::uuid[])
ORDER BY budget_id, category_id
`

type ListBudgetLinesForBudgetsRow struct {
	BudgetID   pgtype.UUID
	CategoryID pgtype.UUID
	CapMinor   int64
}

func (q *Queries) ListBudgetLinesForBudgets(ctx context.Context, budgetIds []pgtype.UUID) ([]ListBudgetLinesForBudgetsRow, error) {
	rows, err := q.db.Query(ctx, listBudgetLinesForBudgets, budgetIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBudgetLinesForBudgetsRow
	for rows.Next() {
		var i ListBudgetLinesForBudgetsRow
		if err := rows.Scan(&i.BudgetID, &i.CategoryID, &i.CapMinor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBudgetsInRange = `-- name: ListBudgetsInRange :many
SELECT b.id, b.household_id, b.month, b.expected_income_minor, h.primary_currency
FROM budgets b
JOIN households h ON h.id = b.household_id
WHERE b.household_id = $1 AND b.month BETWEEN $2 AND $3
ORDER BY b.month DESC
`

type ListBudgetsInRangeParams struct {
	HouseholdID pgtype.UUID
	FromMonth   pgtype.Date
	ToMonth     pgtype.Date
}

type ListBudgetsInRangeRow struct {
	ID                  pgtype.UUID
	HouseholdID         pgtype.UUID
	Month               pgtype.Date
	ExpectedIncomeMinor *int64
	PrimaryCurrency     string
}

// ListBudgetsInRange returns the household's budgeted months between
// from_month and month inclusive, newest first. Because it is a filter over
// rows that already exist rather than a per-month generation, an unbudgeted
// month in that range is simply absent from the result -- which is what
// gives BudgetRepository.History's "[from, month), plus the viewed month if
// budgeted" contract for free: month is included in the BETWEEN, so its row
// comes back exactly when there is one, and the closed months before it come
// back the same way with no special-casing.
func (q *Queries) ListBudgetsInRange(ctx context.Context, arg ListBudgetsInRangeParams) ([]ListBudgetsInRangeRow, error) {
	rows, err := q.db.Query(ctx, listBudgetsInRange, arg.HouseholdID, arg.FromMonth, arg.ToMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBudgetsInRangeRow
	for rows.Next() {
		var i ListBudgetsInRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Month,
			&i.ExpectedIncomeMinor,
			&i.PrimaryCurrency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBudget = `-- name: UpsertBudget :one
INSERT INTO budgets (household_id, month, expected_income_minor)
VALUES ($1, $2, $3)
ON CONFLICT (household_id, month) DO UPDATE
SET expected_income_minor = EXCLUDED.expected_income_minor, updated_at = now()
RETURNING id, household_id, month, expected_income_minor
`

type UpsertBudgetParams struct {
	HouseholdID         pgtype.UUID
	Month               pgtype.Date
	ExpectedIncomeMinor *int64
}

type UpsertBudgetRow struct {
	ID                  pgtype.UUID
	HouseholdID         pgtype.UUID
	Month               pgtype.Date
	ExpectedIncomeMinor *int64
}

// UpsertBudget upserts the parent row on (household_id, month) -- the
// constraint BudgetRepository.Upsert's port doc comment names -- and returns
// the id the lines below attach to, whether that id is new or already
// existed. It never touches budget_lines; BudgetRepo.Upsert deletes and
// rewrites them as separate statements in the same transaction, so a
// category-ownership failure caught before this point leaves neither the
// parent nor the lines touched at all.
func (q *Queries) UpsertBudget(ctx context.Context, arg UpsertBudgetParams) (UpsertBudgetRow, error) {
	row := q.db.QueryRow(ctx, upsertBudget, arg.HouseholdID, arg.Month, arg.ExpectedIncomeMinor)
	var i UpsertBudgetRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Month,
		&i.ExpectedIncomeMinor,
	)
	return i, err
}
