// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: holding.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countLiveHoldingsForAccount = `-- name: CountLiveHoldingsForAccount :one
SELECT COUNT(*)::bigint FROM holdings
WHERE household_id = $1 AND account_id = $2 AND archived_at IS NULL
`

type CountLiveHoldingsForAccountParams struct {
	HouseholdID pgtype.UUID
	AccountID   pgtype.UUID
}

// CountLiveHoldingsForAccount is what stops an account's type being changed
// out from under its holdings. usecase/account.go patches type freely, so a
// cash account could otherwise end up holding 300g of gold.
func (q *Queries) CountLiveHoldingsForAccount(ctx context.Context, arg CountLiveHoldingsForAccountParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveHoldingsForAccount, arg.HouseholdID, arg.AccountID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createHolding = `-- name: CreateHolding :one
INSERT INTO holdings (household_id, account_id, name, instrument, unit, currency)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, household_id, account_id, name, instrument, unit, currency, archived_at, created_at, updated_at
`

type CreateHoldingParams struct {
	HouseholdID pgtype.UUID
	AccountID   pgtype.UUID
	Name        string
	Instrument  string
	Unit        string
	Currency    string
}

// CreateHolding inserts one holding. A name collision -- archived rows
// included, since archived_at is not part of the UNIQUE (account_id, name)
// key -- surfaces as a 23505 that translate maps to domain.ErrHoldingNameTaken
// by constraint name, the same pattern CreateGoal and CreateCategory follow.
func (q *Queries) CreateHolding(ctx context.Context, arg CreateHoldingParams) (Holding, error) {
	row := q.db.QueryRow(ctx, createHolding,
		arg.HouseholdID,
		arg.AccountID,
		arg.Name,
		arg.Instrument,
		arg.Unit,
		arg.Currency,
	)
	var i Holding
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.AccountID,
		&i.Name,
		&i.Instrument,
		&i.Unit,
		&i.Currency,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteHoldingEvent = `-- name: DeleteHoldingEvent :execrows
DELETE FROM holding_events WHERE household_id = $1 AND id = $2
`

type DeleteHoldingEventParams struct {
	HouseholdID pgtype.UUID
	ID          pgtype.UUID
}

func (q *Queries) DeleteHoldingEvent(ctx context.Context, arg DeleteHoldingEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteHoldingEvent, arg.HouseholdID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteValuation = `-- name: DeleteValuation :execrows
DELETE FROM holding_valuations WHERE household_id = $1 AND id = $2
`

type DeleteValuationParams struct {
	HouseholdID pgtype.UUID
	ID          pgtype.UUID
}

func (q *Queries) DeleteValuation(ctx context.Context, arg DeleteValuationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteValuation, arg.HouseholdID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getHolding = `-- name: GetHolding :one
SELECT id, household_id, account_id, name, instrument, unit, currency, archived_at, created_at, updated_at
FROM holdings
WHERE household_id = $1 AND id = $2
`

type GetHoldingParams struct {
	HouseholdID pgtype.UUID
	ID          pgtype.UUID
}

// GetHolding is scoped by household as well as id: a holding id belonging to
// another household must read as absent, never as forbidden, so nothing leaks
// the existence of another household's rows.
func (q *Queries) GetHolding(ctx context.Context, arg GetHoldingParams) (Holding, error) {
	row := q.db.QueryRow(ctx, getHolding, arg.HouseholdID, arg.ID)
	var i Holding
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.AccountID,
		&i.Name,
		&i.Instrument,
		&i.Unit,
		&i.Currency,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertHoldingEvent = `-- name: InsertHoldingEvent :one
INSERT INTO holding_events (holding_id, household_id, kind, quantity_nano, amount_minor,
                            primary_amount_minor, primary_currency, occurred_on, note)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, holding_id, household_id, kind, quantity_nano, amount_minor,
          primary_amount_minor, primary_currency, occurred_on, note, created_at
`

type InsertHoldingEventParams struct {
	HoldingID          pgtype.UUID
	HouseholdID        pgtype.UUID
	Kind               string
	QuantityNano       int64
	AmountMinor        int64
	PrimaryAmountMinor *int64
	PrimaryCurrency    *string
	OccurredOn         pgtype.Date
	Note               string
}

func (q *Queries) InsertHoldingEvent(ctx context.Context, arg InsertHoldingEventParams) (HoldingEvent, error) {
	row := q.db.QueryRow(ctx, insertHoldingEvent,
		arg.HoldingID,
		arg.HouseholdID,
		arg.Kind,
		arg.QuantityNano,
		arg.AmountMinor,
		arg.PrimaryAmountMinor,
		arg.PrimaryCurrency,
		arg.OccurredOn,
		arg.Note,
	)
	var i HoldingEvent
	err := row.Scan(
		&i.ID,
		&i.HoldingID,
		&i.HouseholdID,
		&i.Kind,
		&i.QuantityNano,
		&i.AmountMinor,
		&i.PrimaryAmountMinor,
		&i.PrimaryCurrency,
		&i.OccurredOn,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listHoldingEvents = `-- name: ListHoldingEvents :many
SELECT e.id, e.holding_id, e.household_id, e.kind, e.quantity_nano, e.amount_minor,
       e.primary_amount_minor, e.primary_currency, e.occurred_on, e.note, e.created_at,
       h.currency
FROM holding_events e
JOIN holdings h ON h.id = e.holding_id
WHERE e.household_id = $1 AND e.holding_id = $2
ORDER BY e.occurred_on, e.created_at, e.id
`

type ListHoldingEventsParams struct {
	HouseholdID pgtype.UUID
	HoldingID   pgtype.UUID
}

type ListHoldingEventsRow struct {
	ID                 pgtype.UUID
	HoldingID          pgtype.UUID
	HouseholdID        pgtype.UUID
	Kind               string
	QuantityNano       int64
	AmountMinor        int64
	PrimaryAmountMinor *int64
	PrimaryCurrency    *string
	OccurredOn         pgtype.Date
	Note               string
	CreatedAt          pgtype.Timestamptz
	Currency           string
}

// ListHoldingEvents is the fold's input and its ORDER BY is a CONTRACT, not a
// preference. occurred_on is a date, so two events can share one, and
// domain.Holding.Position sorts stably -- meaning it keeps whatever order it
// is handed for a tie. The tie is therefore broken here, by the order the
// events were actually recorded in (created_at, then id).
//
// Change this ordering and a household's realised gain changes with it,
// silently: on identical same-day events, buy-then-sell realises 750 where
// sell-then-buy realises 1000. holding_events_fold_idx exists for exactly
// this clause.
func (q *Queries) ListHoldingEvents(ctx context.Context, arg ListHoldingEventsParams) ([]ListHoldingEventsRow, error) {
	rows, err := q.db.Query(ctx, listHoldingEvents, arg.HouseholdID, arg.HoldingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHoldingEventsRow
	for rows.Next() {
		var i ListHoldingEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.HoldingID,
			&i.HouseholdID,
			&i.Kind,
			&i.QuantityNano,
			&i.AmountMinor,
			&i.PrimaryAmountMinor,
			&i.PrimaryCurrency,
			&i.OccurredOn,
			&i.Note,
			&i.CreatedAt,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHoldingEventsForHousehold = `-- name: ListHoldingEventsForHousehold :many
SELECT e.id, e.holding_id, e.household_id, e.kind, e.quantity_nano, e.amount_minor,
       e.primary_amount_minor, e.primary_currency, e.occurred_on, e.note, e.created_at,
       h.currency
FROM holding_events e
JOIN holdings h ON h.id = e.holding_id
WHERE e.household_id = $1
ORDER BY e.holding_id, e.occurred_on, e.created_at, e.id
`

type ListHoldingEventsForHouseholdRow struct {
	ID                 pgtype.UUID
	HoldingID          pgtype.UUID
	HouseholdID        pgtype.UUID
	Kind               string
	QuantityNano       int64
	AmountMinor        int64
	PrimaryAmountMinor *int64
	PrimaryCurrency    *string
	OccurredOn         pgtype.Date
	Note               string
	CreatedAt          pgtype.Timestamptz
	Currency           string
}

// ListHoldingEventsForHousehold is the same contract across every holding, so
// the portfolio page folds each position without one query per holding.
func (q *Queries) ListHoldingEventsForHousehold(ctx context.Context, householdID pgtype.UUID) ([]ListHoldingEventsForHouseholdRow, error) {
	rows, err := q.db.Query(ctx, listHoldingEventsForHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHoldingEventsForHouseholdRow
	for rows.Next() {
		var i ListHoldingEventsForHouseholdRow
		if err := rows.Scan(
			&i.ID,
			&i.HoldingID,
			&i.HouseholdID,
			&i.Kind,
			&i.QuantityNano,
			&i.AmountMinor,
			&i.PrimaryAmountMinor,
			&i.PrimaryCurrency,
			&i.OccurredOn,
			&i.Note,
			&i.CreatedAt,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHoldings = `-- name: ListHoldings :many
SELECT h.id, h.household_id, h.account_id, h.name, h.instrument, h.unit, h.currency, h.archived_at, h.created_at, h.updated_at,
       a.nickname AS account_name,
       (a.archived_at IS NOT NULL)::boolean AS account_archived
FROM holdings h
JOIN accounts a ON a.id = h.account_id
WHERE h.household_id = $1 AND (h.archived_at IS NULL OR $2::boolean)
ORDER BY h.name, h.id
`

type ListHoldingsParams struct {
	HouseholdID     pgtype.UUID
	IncludeArchived bool
}

type ListHoldingsRow struct {
	ID              pgtype.UUID
	HouseholdID     pgtype.UUID
	AccountID       pgtype.UUID
	Name            string
	Instrument      string
	Unit            string
	Currency        string
	ArchivedAt      pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	AccountName     string
	AccountArchived bool
}

// ListHoldings returns one household's holdings in a stable name order,
// joined to the account they sit in so a screen can name it. include_archived
// matches ListGoalsWithTotals: false returns only live holdings, true returns
// live and archived together, each carrying its own archived_at.
func (q *Queries) ListHoldings(ctx context.Context, arg ListHoldingsParams) ([]ListHoldingsRow, error) {
	rows, err := q.db.Query(ctx, listHoldings, arg.HouseholdID, arg.IncludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHoldingsRow
	for rows.Next() {
		var i ListHoldingsRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.AccountID,
			&i.Name,
			&i.Instrument,
			&i.Unit,
			&i.Currency,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccountName,
			&i.AccountArchived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestValuations = `-- name: ListLatestValuations :many
SELECT DISTINCT ON (v.holding_id)
       v.id, v.holding_id, v.household_id, v.unit_price_minor, v.primary_unit_price_minor,
       v.primary_currency, v.as_of, v.note, v.created_at, h.currency
FROM holding_valuations v
JOIN holdings h ON h.id = v.holding_id
WHERE v.household_id = $1
ORDER BY v.holding_id, v.as_of DESC, v.id
`

type ListLatestValuationsRow struct {
	ID                    pgtype.UUID
	HoldingID             pgtype.UUID
	HouseholdID           pgtype.UUID
	UnitPriceMinor        int64
	PrimaryUnitPriceMinor *int64
	PrimaryCurrency       *string
	AsOf                  pgtype.Date
	Note                  string
	CreatedAt             pgtype.Timestamptz
	Currency              string
}

// ListLatestValuations is one row per holding: the newest price each has. A
// holding with no valuation at all produces NO ROW rather than a zero one --
// the caller reads an absent holding as "no price recorded", which is what it
// must show on screen rather than a figure of zero.
func (q *Queries) ListLatestValuations(ctx context.Context, householdID pgtype.UUID) ([]ListLatestValuationsRow, error) {
	rows, err := q.db.Query(ctx, listLatestValuations, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestValuationsRow
	for rows.Next() {
		var i ListLatestValuationsRow
		if err := rows.Scan(
			&i.ID,
			&i.HoldingID,
			&i.HouseholdID,
			&i.UnitPriceMinor,
			&i.PrimaryUnitPriceMinor,
			&i.PrimaryCurrency,
			&i.AsOf,
			&i.Note,
			&i.CreatedAt,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listValuations = `-- name: ListValuations :many
SELECT v.id, v.holding_id, v.household_id, v.unit_price_minor, v.primary_unit_price_minor,
       v.primary_currency, v.as_of, v.note, v.created_at, h.currency
FROM holding_valuations v
JOIN holdings h ON h.id = v.holding_id
WHERE v.household_id = $1 AND v.holding_id = $2
ORDER BY v.as_of DESC, v.id
`

type ListValuationsParams struct {
	HouseholdID pgtype.UUID
	HoldingID   pgtype.UUID
}

type ListValuationsRow struct {
	ID                    pgtype.UUID
	HoldingID             pgtype.UUID
	HouseholdID           pgtype.UUID
	UnitPriceMinor        int64
	PrimaryUnitPriceMinor *int64
	PrimaryCurrency       *string
	AsOf                  pgtype.Date
	Note                  string
	CreatedAt             pgtype.Timestamptz
	Currency              string
}

func (q *Queries) ListValuations(ctx context.Context, arg ListValuationsParams) ([]ListValuationsRow, error) {
	rows, err := q.db.Query(ctx, listValuations, arg.HouseholdID, arg.HoldingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListValuationsRow
	for rows.Next() {
		var i ListValuationsRow
		if err := rows.Scan(
			&i.ID,
			&i.HoldingID,
			&i.HouseholdID,
			&i.UnitPriceMinor,
			&i.PrimaryUnitPriceMinor,
			&i.PrimaryCurrency,
			&i.AsOf,
			&i.Note,
			&i.CreatedAt,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setHoldingArchived = `-- name: SetHoldingArchived :one
UPDATE holdings
SET archived_at = $3::timestamptz, updated_at = now()
WHERE household_id = $1 AND id = $2
RETURNING id, household_id, account_id, name, instrument, unit, currency, archived_at, created_at, updated_at
`

type SetHoldingArchivedParams struct {
	HouseholdID pgtype.UUID
	ID          pgtype.UUID
	ArchivedAt  pgtype.Timestamptz
}

func (q *Queries) SetHoldingArchived(ctx context.Context, arg SetHoldingArchivedParams) (Holding, error) {
	row := q.db.QueryRow(ctx, setHoldingArchived, arg.HouseholdID, arg.ID, arg.ArchivedAt)
	var i Holding
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.AccountID,
		&i.Name,
		&i.Instrument,
		&i.Unit,
		&i.Currency,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateHolding = `-- name: UpdateHolding :one
UPDATE holdings
SET name = $3, instrument = $4, unit = $5, updated_at = now()
WHERE household_id = $1 AND id = $2
RETURNING id, household_id, account_id, name, instrument, unit, currency, archived_at, created_at, updated_at
`

type UpdateHoldingParams struct {
	HouseholdID pgtype.UUID
	ID          pgtype.UUID
	Name        string
	Instrument  string
	Unit        string
}

// UpdateHolding changes the editable fields. Neither currency nor account_id
// is among them: a holding's currency is what every one of its events is
// denominated in, and moving a holding between accounts would move money
// between accounts without a ledger row to say so. Both are recreate-only.
func (q *Queries) UpdateHolding(ctx context.Context, arg UpdateHoldingParams) (Holding, error) {
	row := q.db.QueryRow(ctx, updateHolding,
		arg.HouseholdID,
		arg.ID,
		arg.Name,
		arg.Instrument,
		arg.Unit,
	)
	var i Holding
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.AccountID,
		&i.Name,
		&i.Instrument,
		&i.Unit,
		&i.Currency,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertValuation = `-- name: UpsertValuation :one
INSERT INTO holding_valuations (holding_id, household_id, unit_price_minor,
                                primary_unit_price_minor, primary_currency, as_of, note)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (holding_id, as_of) DO UPDATE
SET unit_price_minor = EXCLUDED.unit_price_minor,
    primary_unit_price_minor = EXCLUDED.primary_unit_price_minor,
    primary_currency = EXCLUDED.primary_currency,
    note = EXCLUDED.note
RETURNING id, holding_id, household_id, unit_price_minor, primary_unit_price_minor,
          primary_currency, as_of, note, created_at
`

type UpsertValuationParams struct {
	HoldingID             pgtype.UUID
	HouseholdID           pgtype.UUID
	UnitPriceMinor        int64
	PrimaryUnitPriceMinor *int64
	PrimaryCurrency       *string
	AsOf                  pgtype.Date
	Note                  string
}

// UpsertValuation writes one price per holding per day. Re-entering a day's
// price is a correction, not a second opinion, so the UNIQUE (holding_id,
// as_of) key turns the second write into an update -- which removes the
// question of which of two rows for one day the report should believe.
func (q *Queries) UpsertValuation(ctx context.Context, arg UpsertValuationParams) (HoldingValuation, error) {
	row := q.db.QueryRow(ctx, upsertValuation,
		arg.HoldingID,
		arg.HouseholdID,
		arg.UnitPriceMinor,
		arg.PrimaryUnitPriceMinor,
		arg.PrimaryCurrency,
		arg.AsOf,
		arg.Note,
	)
	var i HoldingValuation
	err := row.Scan(
		&i.ID,
		&i.HoldingID,
		&i.HouseholdID,
		&i.UnitPriceMinor,
		&i.PrimaryUnitPriceMinor,
		&i.PrimaryCurrency,
		&i.AsOf,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}
