// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: holding_income.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteHoldingIncome = `-- name: DeleteHoldingIncome :execrows
DELETE FROM holding_income
WHERE household_id = $1 AND holding_id = $2 AND id = $3
`

type DeleteHoldingIncomeParams struct {
	HouseholdID pgtype.UUID
	HoldingID   pgtype.UUID
	ID          pgtype.UUID
}

// DeleteHoldingIncome is scoped to the HOLDING as well as the household, so a
// request naming one holding cannot remove another's row. The household alone
// would be enough to keep the households apart -- this is about the URL and
// the database agreeing on which holding is being edited.
func (q *Queries) DeleteHoldingIncome(ctx context.Context, arg DeleteHoldingIncomeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteHoldingIncome, arg.HouseholdID, arg.HoldingID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertHoldingIncome = `-- name: InsertHoldingIncome :one
INSERT INTO holding_income (holding_id, household_id, kind, amount_minor,
                            primary_amount_minor, primary_currency, received_on, note)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, holding_id, household_id, kind, amount_minor,
          primary_amount_minor, primary_currency, received_on, note, created_at
`

type InsertHoldingIncomeParams struct {
	HoldingID          pgtype.UUID
	HouseholdID        pgtype.UUID
	Kind               string
	AmountMinor        int64
	PrimaryAmountMinor *int64
	PrimaryCurrency    *string
	ReceivedOn         pgtype.Date
	Note               string
}

func (q *Queries) InsertHoldingIncome(ctx context.Context, arg InsertHoldingIncomeParams) (HoldingIncome, error) {
	row := q.db.QueryRow(ctx, insertHoldingIncome,
		arg.HoldingID,
		arg.HouseholdID,
		arg.Kind,
		arg.AmountMinor,
		arg.PrimaryAmountMinor,
		arg.PrimaryCurrency,
		arg.ReceivedOn,
		arg.Note,
	)
	var i HoldingIncome
	err := row.Scan(
		&i.ID,
		&i.HoldingID,
		&i.HouseholdID,
		&i.Kind,
		&i.AmountMinor,
		&i.PrimaryAmountMinor,
		&i.PrimaryCurrency,
		&i.ReceivedOn,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listHoldingIncome = `-- name: ListHoldingIncome :many
SELECT i.id, i.holding_id, i.household_id, i.kind, i.amount_minor,
       i.primary_amount_minor, i.primary_currency, i.received_on, i.note, i.created_at,
       h.currency
FROM holding_income i
JOIN holdings h ON h.id = i.holding_id
WHERE i.household_id = $1 AND i.holding_id = $2
ORDER BY i.received_on DESC, i.id
`

type ListHoldingIncomeParams struct {
	HouseholdID pgtype.UUID
	HoldingID   pgtype.UUID
}

type ListHoldingIncomeRow struct {
	ID                 pgtype.UUID
	HoldingID          pgtype.UUID
	HouseholdID        pgtype.UUID
	Kind               string
	AmountMinor        int64
	PrimaryAmountMinor *int64
	PrimaryCurrency    *string
	ReceivedOn         pgtype.Date
	Note               string
	CreatedAt          pgtype.Timestamptz
	Currency           string
}

// ListHoldingIncome is one holding's rows, newest first, the way a panel under
// the holding reads them. The order is a PRESENTATION choice here and nothing
// computes with it -- summing a period is commutative, unlike the event fold
// whose ORDER BY is a contract.
func (q *Queries) ListHoldingIncome(ctx context.Context, arg ListHoldingIncomeParams) ([]ListHoldingIncomeRow, error) {
	rows, err := q.db.Query(ctx, listHoldingIncome, arg.HouseholdID, arg.HoldingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHoldingIncomeRow
	for rows.Next() {
		var i ListHoldingIncomeRow
		if err := rows.Scan(
			&i.ID,
			&i.HoldingID,
			&i.HouseholdID,
			&i.Kind,
			&i.AmountMinor,
			&i.PrimaryAmountMinor,
			&i.PrimaryCurrency,
			&i.ReceivedOn,
			&i.Note,
			&i.CreatedAt,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHoldingIncomeForHousehold = `-- name: ListHoldingIncomeForHousehold :many
SELECT i.id, i.holding_id, i.household_id, i.kind, i.amount_minor,
       i.primary_amount_minor, i.primary_currency, i.received_on, i.note, i.created_at,
       h.currency
FROM holding_income i
JOIN holdings h ON h.id = i.holding_id
WHERE i.household_id = $1
ORDER BY i.holding_id, i.received_on, i.id
`

type ListHoldingIncomeForHouseholdRow struct {
	ID                 pgtype.UUID
	HoldingID          pgtype.UUID
	HouseholdID        pgtype.UUID
	Kind               string
	AmountMinor        int64
	PrimaryAmountMinor *int64
	PrimaryCurrency    *string
	ReceivedOn         pgtype.Date
	Note               string
	CreatedAt          pgtype.Timestamptz
	Currency           string
}

// ListHoldingIncomeForHousehold is every row the period report needs, in one
// read rather than one query per holding -- the same shape
// ListHoldingEventsForHousehold uses and for the same reason.
func (q *Queries) ListHoldingIncomeForHousehold(ctx context.Context, householdID pgtype.UUID) ([]ListHoldingIncomeForHouseholdRow, error) {
	rows, err := q.db.Query(ctx, listHoldingIncomeForHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHoldingIncomeForHouseholdRow
	for rows.Next() {
		var i ListHoldingIncomeForHouseholdRow
		if err := rows.Scan(
			&i.ID,
			&i.HoldingID,
			&i.HouseholdID,
			&i.Kind,
			&i.AmountMinor,
			&i.PrimaryAmountMinor,
			&i.PrimaryCurrency,
			&i.ReceivedOn,
			&i.Note,
			&i.CreatedAt,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
