// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: identity.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearFailures = `-- name: ClearFailures :exec
DELETE FROM login_attempts WHERE household_id = $1 AND succeeded = false
`

func (q *Queries) ClearFailures(ctx context.Context, householdID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearFailures, householdID)
	return err
}

const consumeMagicLink = `-- name: ConsumeMagicLink :one
UPDATE magic_links SET consumed_at = now()
WHERE token_hash = $1 AND consumed_at IS NULL AND expires_at > now()
RETURNING user_id
`

func (q *Queries) ConsumeMagicLink(ctx context.Context, tokenHash []byte) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, consumeMagicLink, tokenHash)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const countRecentMagicLinks = `-- name: CountRecentMagicLinks :one
SELECT count(*) FROM magic_links m JOIN users u ON u.id = m.user_id
WHERE u.email = $1 AND m.created_at > $2
`

type CountRecentMagicLinksParams struct {
	Email     *string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CountRecentMagicLinks(ctx context.Context, arg CountRecentMagicLinksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentMagicLinks, arg.Email, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHousehold = `-- name: CreateHousehold :one
INSERT INTO households (name, family_name) VALUES ($1, $2)
RETURNING id, name, family_name, primary_currency, show_secondary_currency,
          secondary_currency, fx_rate_mode
`

type CreateHouseholdParams struct {
	Name       string
	FamilyName string
}

type CreateHouseholdRow struct {
	ID                    pgtype.UUID
	Name                  string
	FamilyName            string
	PrimaryCurrency       string
	ShowSecondaryCurrency bool
	SecondaryCurrency     string
	FxRateMode            string
}

func (q *Queries) CreateHousehold(ctx context.Context, arg CreateHouseholdParams) (CreateHouseholdRow, error) {
	row := q.db.QueryRow(ctx, createHousehold, arg.Name, arg.FamilyName)
	var i CreateHouseholdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FamilyName,
		&i.PrimaryCurrency,
		&i.ShowSecondaryCurrency,
		&i.SecondaryCurrency,
		&i.FxRateMode,
	)
	return i, err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (household_id, email, name, role, capabilities, token_hash, invited_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type CreateInviteParams struct {
	HouseholdID  pgtype.UUID
	Email        string
	Name         string
	Role         string
	Capabilities []string
	TokenHash    []byte
	InvitedBy    pgtype.UUID
	ExpiresAt    pgtype.Timestamptz
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.HouseholdID,
		arg.Email,
		arg.Name,
		arg.Role,
		arg.Capabilities,
		arg.TokenHash,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createMagicLink = `-- name: CreateMagicLink :exec
INSERT INTO magic_links (user_id, token_hash, expires_at) VALUES ($1, $2, $3)
`

type CreateMagicLinkParams struct {
	UserID    pgtype.UUID
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateMagicLink(ctx context.Context, arg CreateMagicLinkParams) error {
	_, err := q.db.Exec(ctx, createMagicLink, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (household_id, user_id, role, capabilities)
VALUES ($1, $2, $3, $4)
RETURNING id, household_id, user_id, role, capabilities
`

type CreateMembershipParams struct {
	HouseholdID  pgtype.UUID
	UserID       pgtype.UUID
	Role         string
	Capabilities []string
}

type CreateMembershipRow struct {
	ID           pgtype.UUID
	HouseholdID  pgtype.UUID
	UserID       pgtype.UUID
	Role         string
	Capabilities []string
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (CreateMembershipRow, error) {
	row := q.db.QueryRow(ctx, createMembership,
		arg.HouseholdID,
		arg.UserID,
		arg.Role,
		arg.Capabilities,
	)
	var i CreateMembershipRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.UserID,
		&i.Role,
		&i.Capabilities,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (token_hash, user_id, household_id, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateSessionParams struct {
	TokenHash   []byte
	UserID      pgtype.UUID
	HouseholdID pgtype.UUID
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.HouseholdID,
		arg.ExpiresAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createSpace = `-- name: CreateSpace :one
INSERT INTO spaces (household_id, key, name, visibility, position, is_builtin, required_capability)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, household_id, key, name, visibility, position, is_builtin, required_capability
`

type CreateSpaceParams struct {
	HouseholdID        pgtype.UUID
	Key                string
	Name               string
	Visibility         string
	Position           int32
	IsBuiltin          bool
	RequiredCapability string
}

func (q *Queries) CreateSpace(ctx context.Context, arg CreateSpaceParams) (Space, error) {
	row := q.db.QueryRow(ctx, createSpace,
		arg.HouseholdID,
		arg.Key,
		arg.Name,
		arg.Visibility,
		arg.Position,
		arg.IsBuiltin,
		arg.RequiredCapability,
	)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Key,
		&i.Name,
		&i.Visibility,
		&i.Position,
		&i.IsBuiltin,
		&i.RequiredCapability,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, display_name, avatar_initial)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, display_name, avatar_initial
`

type CreateUserParams struct {
	Email         *string
	PasswordHash  *string
	DisplayName   string
	AvatarInitial string
}

type CreateUserRow struct {
	ID            pgtype.UUID
	Email         *string
	PasswordHash  *string
	DisplayName   string
	AvatarInitial string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.AvatarInitial,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarInitial,
	)
	return i, err
}

const deleteMembership = `-- name: DeleteMembership :exec
DELETE FROM memberships WHERE household_id = $1 AND id = $2
`

type DeleteMembershipParams struct {
	HouseholdID pgtype.UUID
	ID          pgtype.UUID
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error {
	_, err := q.db.Exec(ctx, deleteMembership, arg.HouseholdID, arg.ID)
	return err
}

const extendSession = `-- name: ExtendSession :exec
UPDATE sessions SET expires_at = $2 WHERE token_hash = $1
`

type ExtendSessionParams struct {
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) ExtendSession(ctx context.Context, arg ExtendSessionParams) error {
	_, err := q.db.Exec(ctx, extendSession, arg.TokenHash, arg.ExpiresAt)
	return err
}

const getHousehold = `-- name: GetHousehold :one
SELECT id, name, family_name, primary_currency, show_secondary_currency,
       secondary_currency, fx_rate_mode
FROM households WHERE id = $1
`

type GetHouseholdRow struct {
	ID                    pgtype.UUID
	Name                  string
	FamilyName            string
	PrimaryCurrency       string
	ShowSecondaryCurrency bool
	SecondaryCurrency     string
	FxRateMode            string
}

func (q *Queries) GetHousehold(ctx context.Context, id pgtype.UUID) (GetHouseholdRow, error) {
	row := q.db.QueryRow(ctx, getHousehold, id)
	var i GetHouseholdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FamilyName,
		&i.PrimaryCurrency,
		&i.ShowSecondaryCurrency,
		&i.SecondaryCurrency,
		&i.FxRateMode,
	)
	return i, err
}

const getInviteByTokenHash = `-- name: GetInviteByTokenHash :one
SELECT i.id, i.household_id, i.email, i.name, i.role, i.capabilities,
       i.expires_at, i.accepted_at, h.family_name, u.display_name AS inviter_name
FROM invites i
JOIN households h ON h.id = i.household_id
JOIN users u ON u.id = i.invited_by
WHERE i.token_hash = $1
`

type GetInviteByTokenHashRow struct {
	ID           pgtype.UUID
	HouseholdID  pgtype.UUID
	Email        string
	Name         string
	Role         string
	Capabilities []string
	ExpiresAt    pgtype.Timestamptz
	AcceptedAt   pgtype.Timestamptz
	FamilyName   string
	InviterName  string
}

func (q *Queries) GetInviteByTokenHash(ctx context.Context, tokenHash []byte) (GetInviteByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getInviteByTokenHash, tokenHash)
	var i GetInviteByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.Capabilities,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.FamilyName,
		&i.InviterName,
	)
	return i, err
}

const getLiveSession = `-- name: GetLiveSession :one
SELECT id, user_id, household_id, expires_at FROM sessions
WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > now()
`

type GetLiveSessionRow struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	HouseholdID pgtype.UUID
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) GetLiveSession(ctx context.Context, tokenHash []byte) (GetLiveSessionRow, error) {
	row := q.db.QueryRow(ctx, getLiveSession, tokenHash)
	var i GetLiveSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.HouseholdID,
		&i.ExpiresAt,
	)
	return i, err
}

const getMembershipByUser = `-- name: GetMembershipByUser :one
SELECT id, household_id, user_id, role, capabilities
FROM memberships WHERE user_id = $1 LIMIT 1
`

type GetMembershipByUserRow struct {
	ID           pgtype.UUID
	HouseholdID  pgtype.UUID
	UserID       pgtype.UUID
	Role         string
	Capabilities []string
}

func (q *Queries) GetMembershipByUser(ctx context.Context, userID pgtype.UUID) (GetMembershipByUserRow, error) {
	row := q.db.QueryRow(ctx, getMembershipByUser, userID)
	var i GetMembershipByUserRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.UserID,
		&i.Role,
		&i.Capabilities,
	)
	return i, err
}

const getNotificationPreferences = `-- name: GetNotificationPreferences :one
SELECT household_id, bill_reminders, overspend_alerts, retro_reminder, weekly_digest
FROM notification_preferences WHERE household_id = $1
`

func (q *Queries) GetNotificationPreferences(ctx context.Context, householdID pgtype.UUID) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, getNotificationPreferences, householdID)
	var i NotificationPreference
	err := row.Scan(
		&i.HouseholdID,
		&i.BillReminders,
		&i.OverspendAlerts,
		&i.RetroReminder,
		&i.WeeklyDigest,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, display_name, avatar_initial FROM users WHERE email = $1
`

type GetUserByEmailRow struct {
	ID            pgtype.UUID
	Email         *string
	PasswordHash  *string
	DisplayName   string
	AvatarInitial string
}

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarInitial,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, display_name, avatar_initial FROM users WHERE id = $1
`

type GetUserByIDRow struct {
	ID            pgtype.UUID
	Email         *string
	PasswordHash  *string
	DisplayName   string
	AvatarInitial string
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarInitial,
	)
	return i, err
}

const listMemberships = `-- name: ListMemberships :many
SELECT m.id, m.household_id, m.user_id, m.role, m.capabilities,
       u.email, u.display_name, u.avatar_initial
FROM memberships m JOIN users u ON u.id = m.user_id
WHERE m.household_id = $1
ORDER BY m.role DESC, u.display_name
`

type ListMembershipsRow struct {
	ID            pgtype.UUID
	HouseholdID   pgtype.UUID
	UserID        pgtype.UUID
	Role          string
	Capabilities  []string
	Email         *string
	DisplayName   string
	AvatarInitial string
}

func (q *Queries) ListMemberships(ctx context.Context, householdID pgtype.UUID) ([]ListMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listMemberships, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembershipsRow
	for rows.Next() {
		var i ListMembershipsRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.UserID,
			&i.Role,
			&i.Capabilities,
			&i.Email,
			&i.DisplayName,
			&i.AvatarInitial,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentFailures = `-- name: ListRecentFailures :many
SELECT at FROM login_attempts
WHERE household_id = $1 AND succeeded = false AND at > $2
ORDER BY at DESC
`

type ListRecentFailuresParams struct {
	HouseholdID pgtype.UUID
	At          pgtype.Timestamptz
}

func (q *Queries) ListRecentFailures(ctx context.Context, arg ListRecentFailuresParams) ([]pgtype.Timestamptz, error) {
	rows, err := q.db.Query(ctx, listRecentFailures, arg.HouseholdID, arg.At)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Timestamptz
	for rows.Next() {
		var at pgtype.Timestamptz
		if err := rows.Scan(&at); err != nil {
			return nil, err
		}
		items = append(items, at)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentFailuresByEmail = `-- name: ListRecentFailuresByEmail :many
SELECT at FROM login_attempts
WHERE email = $1 AND succeeded = false AND at > $2
ORDER BY at DESC
`

type ListRecentFailuresByEmailParams struct {
	Email string
	At    pgtype.Timestamptz
}

func (q *Queries) ListRecentFailuresByEmail(ctx context.Context, arg ListRecentFailuresByEmailParams) ([]pgtype.Timestamptz, error) {
	rows, err := q.db.Query(ctx, listRecentFailuresByEmail, arg.Email, arg.At)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Timestamptz
	for rows.Next() {
		var at pgtype.Timestamptz
		if err := rows.Scan(&at); err != nil {
			return nil, err
		}
		items = append(items, at)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpaces = `-- name: ListSpaces :many
SELECT id, household_id, key, name, visibility, position, is_builtin, required_capability
FROM spaces WHERE household_id = $1 ORDER BY position
`

func (q *Queries) ListSpaces(ctx context.Context, householdID pgtype.UUID) ([]Space, error) {
	rows, err := q.db.Query(ctx, listSpaces, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Space
	for rows.Next() {
		var i Space
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Key,
			&i.Name,
			&i.Visibility,
			&i.Position,
			&i.IsBuiltin,
			&i.RequiredCapability,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInviteAccepted = `-- name: MarkInviteAccepted :one
UPDATE invites SET accepted_at = now()
WHERE id = $1 AND accepted_at IS NULL AND expires_at > now()
RETURNING id
`

func (q *Queries) MarkInviteAccepted(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, markInviteAccepted, id)
	err := row.Scan(&id)
	return id, err
}

const nextSpacePosition = `-- name: NextSpacePosition :one
SELECT coalesce(max(position), 0) + 1 FROM spaces WHERE household_id = $1
`

func (q *Queries) NextSpacePosition(ctx context.Context, householdID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextSpacePosition, householdID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const recordLoginAttempt = `-- name: RecordLoginAttempt :exec
INSERT INTO login_attempts (household_id, user_id, email, succeeded, at)
VALUES ($1, $2, $3, $4, $5)
`

type RecordLoginAttemptParams struct {
	HouseholdID pgtype.UUID
	UserID      pgtype.UUID
	Email       string
	Succeeded   bool
	At          pgtype.Timestamptz
}

func (q *Queries) RecordLoginAttempt(ctx context.Context, arg RecordLoginAttemptParams) error {
	_, err := q.db.Exec(ctx, recordLoginAttempt,
		arg.HouseholdID,
		arg.UserID,
		arg.Email,
		arg.Succeeded,
		arg.At,
	)
	return err
}

const revokeSessionByToken = `-- name: RevokeSessionByToken :exec
UPDATE sessions SET revoked_at = now() WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionByToken(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, revokeSessionByToken, tokenHash)
	return err
}

const revokeSessionsForUser = `-- name: RevokeSessionsForUser :exec
UPDATE sessions SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionsForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeSessionsForUser, userID)
	return err
}

const setPasswordHash = `-- name: SetPasswordHash :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type SetPasswordHashParams struct {
	ID           pgtype.UUID
	PasswordHash *string
}

func (q *Queries) SetPasswordHash(ctx context.Context, arg SetPasswordHashParams) error {
	_, err := q.db.Exec(ctx, setPasswordHash, arg.ID, arg.PasswordHash)
	return err
}

const updateHousehold = `-- name: UpdateHousehold :one
UPDATE households
SET family_name = $2, primary_currency = $3, show_secondary_currency = $4, fx_rate_mode = $5
WHERE id = $1
RETURNING id, name, family_name, primary_currency, show_secondary_currency,
          secondary_currency, fx_rate_mode
`

type UpdateHouseholdParams struct {
	ID                    pgtype.UUID
	FamilyName            string
	PrimaryCurrency       string
	ShowSecondaryCurrency bool
	FxRateMode            string
}

type UpdateHouseholdRow struct {
	ID                    pgtype.UUID
	Name                  string
	FamilyName            string
	PrimaryCurrency       string
	ShowSecondaryCurrency bool
	SecondaryCurrency     string
	FxRateMode            string
}

func (q *Queries) UpdateHousehold(ctx context.Context, arg UpdateHouseholdParams) (UpdateHouseholdRow, error) {
	row := q.db.QueryRow(ctx, updateHousehold,
		arg.ID,
		arg.FamilyName,
		arg.PrimaryCurrency,
		arg.ShowSecondaryCurrency,
		arg.FxRateMode,
	)
	var i UpdateHouseholdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FamilyName,
		&i.PrimaryCurrency,
		&i.ShowSecondaryCurrency,
		&i.SecondaryCurrency,
		&i.FxRateMode,
	)
	return i, err
}

const updateMembership = `-- name: UpdateMembership :exec
UPDATE memberships SET role = $3, capabilities = $4 WHERE household_id = $1 AND id = $2
`

type UpdateMembershipParams struct {
	HouseholdID  pgtype.UUID
	ID           pgtype.UUID
	Role         string
	Capabilities []string
}

func (q *Queries) UpdateMembership(ctx context.Context, arg UpdateMembershipParams) error {
	_, err := q.db.Exec(ctx, updateMembership,
		arg.HouseholdID,
		arg.ID,
		arg.Role,
		arg.Capabilities,
	)
	return err
}

const upsertNotificationPreferences = `-- name: UpsertNotificationPreferences :one
INSERT INTO notification_preferences (household_id, bill_reminders, overspend_alerts, retro_reminder, weekly_digest)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (household_id) DO UPDATE
SET bill_reminders = excluded.bill_reminders,
    overspend_alerts = excluded.overspend_alerts,
    retro_reminder = excluded.retro_reminder,
    weekly_digest = excluded.weekly_digest
RETURNING household_id, bill_reminders, overspend_alerts, retro_reminder, weekly_digest
`

type UpsertNotificationPreferencesParams struct {
	HouseholdID     pgtype.UUID
	BillReminders   bool
	OverspendAlerts bool
	RetroReminder   bool
	WeeklyDigest    bool
}

func (q *Queries) UpsertNotificationPreferences(ctx context.Context, arg UpsertNotificationPreferencesParams) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, upsertNotificationPreferences,
		arg.HouseholdID,
		arg.BillReminders,
		arg.OverspendAlerts,
		arg.RetroReminder,
		arg.WeeklyDigest,
	)
	var i NotificationPreference
	err := row.Scan(
		&i.HouseholdID,
		&i.BillReminders,
		&i.OverspendAlerts,
		&i.RetroReminder,
		&i.WeeklyDigest,
	)
	return i, err
}
