// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                      pgtype.UUID
	HouseholdID             pgtype.UUID
	Nickname                string
	Type                    string
	OwnerMembershipID       pgtype.UUID
	OpeningBalanceMinor     int64
	OpeningBalanceCurrency  string
	OpeningBalanceAsOf      pgtype.Date
	CountTowardNetWorth     bool
	VisibleToLimitedMembers bool
	ArchivedAt              pgtype.Timestamptz
	CreatedAt               pgtype.Timestamptz
}

type Bill struct {
	ID                 pgtype.UUID
	HouseholdID        pgtype.UUID
	Name               string
	AmountMinor        int64
	Cadence            string
	NextDue            pgtype.Date
	DueAnchorDay       int16
	CategoryID         pgtype.UUID
	PayFromAccountID   pgtype.UUID
	PaidByMembershipID pgtype.UUID
	Autopay            bool
	IsSubscription     bool
	ArchivedAt         pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type BillPayment struct {
	ID            pgtype.UUID
	BillID        pgtype.UUID
	HouseholdID   pgtype.UUID
	DueOn         pgtype.Date
	PaidOn        pgtype.Date
	AmountMinor   int64
	TransactionID pgtype.UUID
	CreatedAt     pgtype.Timestamptz
}

type Budget struct {
	ID                  pgtype.UUID
	HouseholdID         pgtype.UUID
	Month               pgtype.Date
	ExpectedIncomeMinor *int64
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	RolledOverAt        pgtype.Timestamptz
	RolloverGoalID      pgtype.UUID
}

type BudgetLine struct {
	ID         pgtype.UUID
	BudgetID   pgtype.UUID
	CategoryID pgtype.UUID
	CapMinor   int64
}

type Category struct {
	ID          pgtype.UUID
	HouseholdID pgtype.UUID
	Name        string
	Kind        string
	SortOrder   int32
	ArchivedAt  pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type Goal struct {
	ID                  pgtype.UUID
	HouseholdID         pgtype.UUID
	Name                string
	TargetAmountMinor   int64
	Currency            string
	TargetMonth         pgtype.Date
	PlannedMonthlyMinor int64
	ArchivedAt          pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type GoalContribution struct {
	ID                pgtype.UUID
	GoalID            pgtype.UUID
	HouseholdID       pgtype.UUID
	AmountMinor       int64
	OccurredOn        pgtype.Date
	Note              string
	Source            string
	SourceBudgetMonth pgtype.Date
	CreatedAt         pgtype.Timestamptz
}

type Household struct {
	ID                    pgtype.UUID
	Name                  string
	FamilyName            string
	PrimaryCurrency       string
	ShowSecondaryCurrency bool
	SecondaryCurrency     string
	FxRateMode            string
	CreatedAt             pgtype.Timestamptz
}

type Invite struct {
	ID           pgtype.UUID
	HouseholdID  pgtype.UUID
	Email        string
	Name         string
	Role         string
	Capabilities []string
	TokenHash    []byte
	InvitedBy    pgtype.UUID
	ExpiresAt    pgtype.Timestamptz
	AcceptedAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type LoginAttempt struct {
	ID          pgtype.UUID
	HouseholdID pgtype.UUID
	UserID      pgtype.UUID
	Email       string
	Succeeded   bool
	At          pgtype.Timestamptz
}

type MagicLink struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	TokenHash  []byte
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type Membership struct {
	ID           pgtype.UUID
	HouseholdID  pgtype.UUID
	UserID       pgtype.UUID
	Role         string
	Capabilities []string
	JoinedAt     pgtype.Timestamptz
}

type NotificationPreference struct {
	HouseholdID     pgtype.UUID
	BillReminders   bool
	OverspendAlerts bool
	RetroReminder   bool
	WeeklyDigest    bool
}

type Session struct {
	ID          pgtype.UUID
	TokenHash   []byte
	UserID      pgtype.UUID
	HouseholdID pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
}

type Signup struct {
	ID         pgtype.UUID
	Email      string
	TokenHash  []byte
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type Space struct {
	ID                 pgtype.UUID
	HouseholdID        pgtype.UUID
	Key                string
	Name               string
	Visibility         string
	Position           int32
	IsBuiltin          bool
	RequiredCapability string
}

type Transaction struct {
	ID                     pgtype.UUID
	HouseholdID            pgtype.UUID
	Kind                   string
	OccurredOn             pgtype.Date
	Description            string
	CategoryID             pgtype.UUID
	PaidByMembershipID     pgtype.UUID
	FromAccountID          pgtype.UUID
	ToAccountID            pgtype.UUID
	AmountMinor            int64
	AmountCurrency         string
	ReceivedAmountMinor    *int64
	ReceivedAmountCurrency *string
	CreatedAt              pgtype.Timestamptz
}

type User struct {
	ID            pgtype.UUID
	Email         *string
	PasswordHash  *string
	DisplayName   string
	AvatarInitial string
	CreatedAt     pgtype.Timestamptz
}
