// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                      pgtype.UUID
	HouseholdID             pgtype.UUID
	Nickname                string
	Type                    string
	OwnerMembershipID       pgtype.UUID
	OpeningBalanceMinor     int64
	OpeningBalanceCurrency  string
	OpeningBalanceAsOf      pgtype.Date
	CountTowardNetWorth     bool
	VisibleToLimitedMembers bool
	ArchivedAt              pgtype.Timestamptz
	CreatedAt               pgtype.Timestamptz
}

type Household struct {
	ID                    pgtype.UUID
	Name                  string
	FamilyName            string
	PrimaryCurrency       string
	ShowSecondaryCurrency bool
	SecondaryCurrency     string
	FxRateMode            string
	CreatedAt             pgtype.Timestamptz
}

type Invite struct {
	ID           pgtype.UUID
	HouseholdID  pgtype.UUID
	Email        string
	Name         string
	Role         string
	Capabilities []string
	TokenHash    []byte
	InvitedBy    pgtype.UUID
	ExpiresAt    pgtype.Timestamptz
	AcceptedAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type LoginAttempt struct {
	ID          pgtype.UUID
	HouseholdID pgtype.UUID
	UserID      pgtype.UUID
	Email       string
	Succeeded   bool
	At          pgtype.Timestamptz
}

type MagicLink struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	TokenHash  []byte
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type Membership struct {
	ID           pgtype.UUID
	HouseholdID  pgtype.UUID
	UserID       pgtype.UUID
	Role         string
	Capabilities []string
	JoinedAt     pgtype.Timestamptz
}

type NotificationPreference struct {
	HouseholdID     pgtype.UUID
	BillReminders   bool
	OverspendAlerts bool
	RetroReminder   bool
	WeeklyDigest    bool
}

type Session struct {
	ID          pgtype.UUID
	TokenHash   []byte
	UserID      pgtype.UUID
	HouseholdID pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
}

type Signup struct {
	ID         pgtype.UUID
	Email      string
	TokenHash  []byte
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type Space struct {
	ID                 pgtype.UUID
	HouseholdID        pgtype.UUID
	Key                string
	Name               string
	Visibility         string
	Position           int32
	IsBuiltin          bool
	RequiredCapability string
}

type User struct {
	ID            pgtype.UUID
	Email         *string
	PasswordHash  *string
	DisplayName   string
	AvatarInitial string
	CreatedAt     pgtype.Timestamptz
}
