// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: nudge.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimNudge = `-- name: ClaimNudge :execrows
INSERT INTO nudge_deliveries (chat_id, household_id, day)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type ClaimNudgeParams struct {
	ChatID      int64
	HouseholdID pgtype.UUID
	Day         pgtype.Date
}

// ClaimNudge is insert-first: zero rows means today's digest for this chat and
// household is already claimed (sent, or being sent), and the caller skips.
func (q *Queries) ClaimNudge(ctx context.Context, arg ClaimNudgeParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimNudge, arg.ChatID, arg.HouseholdID, arg.Day)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listNudgeRecipients = `-- name: ListNudgeRecipients :many
SELECT ta.chat_id, m.household_id, m.id AS membership_id, h.primary_currency
FROM telegram_accounts ta
JOIN memberships m ON m.user_id = ta.user_id
JOIN households h ON h.id = m.household_id
WHERE ta.nudges_enabled
  AND m.role = 'owner'
  AND 'money' = ANY (m.capabilities)
ORDER BY ta.chat_id, m.household_id
`

type ListNudgeRecipientsRow struct {
	ChatID          int64
	HouseholdID     pgtype.UUID
	MembershipID    pgtype.UUID
	PrimaryCurrency string
}

// ListNudgeRecipients is the outbound half of ADR 8's rule: money leaves the
// system only to a chat that could already ask /balance -- an owner with the
// money capability -- and only while that chat has not said /nudges off. The
// role and capability predicates are the authorisation; a test drops each one
// and expects a stranger to appear.
func (q *Queries) ListNudgeRecipients(ctx context.Context) ([]ListNudgeRecipientsRow, error) {
	rows, err := q.db.Query(ctx, listNudgeRecipients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNudgeRecipientsRow
	for rows.Next() {
		var i ListNudgeRecipientsRow
		if err := rows.Scan(
			&i.ChatID,
			&i.HouseholdID,
			&i.MembershipID,
			&i.PrimaryCurrency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneNudgeDeliveries = `-- name: PruneNudgeDeliveries :execrows
DELETE FROM nudge_deliveries WHERE day < $1
`

func (q *Queries) PruneNudgeDeliveries(ctx context.Context, day pgtype.Date) (int64, error) {
	result, err := q.db.Exec(ctx, pruneNudgeDeliveries, day)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseNudge = `-- name: ReleaseNudge :exec
DELETE FROM nudge_deliveries
WHERE chat_id = $1 AND household_id = $2 AND day = $3
`

type ReleaseNudgeParams struct {
	ChatID      int64
	HouseholdID pgtype.UUID
	Day         pgtype.Date
}

// ReleaseNudge undoes a claim whose send failed, so the next tick tries again.
func (q *Queries) ReleaseNudge(ctx context.Context, arg ReleaseNudgeParams) error {
	_, err := q.db.Exec(ctx, releaseNudge, arg.ChatID, arg.HouseholdID, arg.Day)
	return err
}

const setNudgesEnabled = `-- name: SetNudgesEnabled :execrows
UPDATE telegram_accounts SET nudges_enabled = $2 WHERE chat_id = $1
`

type SetNudgesEnabledParams struct {
	ChatID        int64
	NudgesEnabled bool
}

func (q *Queries) SetNudgesEnabled(ctx context.Context, arg SetNudgesEnabledParams) (int64, error) {
	result, err := q.db.Exec(ctx, setNudgesEnabled, arg.ChatID, arg.NudgesEnabled)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
