// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: retro.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRetroAction = `-- name: AddRetroAction :one
INSERT INTO retro_actions (retro_id, body, carried_from)
SELECT r.id, $1, $2
FROM retros r
LEFT JOIN retro_actions ca ON ca.id = $2
LEFT JOIN retros cr ON cr.id = ca.retro_id
WHERE r.id = $3 AND r.household_id = $4
  AND ($2 IS NULL OR cr.household_id = $4)
RETURNING id, retro_id, body, done_at, carried_from
`

type AddRetroActionParams struct {
	Body        string
	CarriedFrom pgtype.UUID
	ID          pgtype.UUID
	HouseholdID pgtype.UUID
}

type AddRetroActionRow struct {
	ID          pgtype.UUID
	RetroID     pgtype.UUID
	Body        string
	DoneAt      pgtype.Timestamptz
	CarriedFrom pgtype.UUID
}

// AddRetroAction writes one action. retro_actions carries no household_id of
// its own (00009_retros.sql's own comment), so the INSERT...SELECT...FROM
// retros WHERE household_id = $4 is the scoping clause, not a plain INSERT
// with a bare retro_id: a retro_id that belongs to another household, or
// does not exist at all, matches zero rows, and :one then reports
// pgx.ErrNoRows -- which translate maps to domain.ErrNotFound, the same
// "another household's row is indistinguishable from a missing one"
// convention GetRetroByMonth already follows.
//
// carried_from ($2) gets the identical treatment, not just the FK
// retro_actions.carried_from already declares: retro_actions ca / retros cr
// LEFT JOIN in the action $2 names, and the WHERE's ($2 IS NULL OR
// cr.household_id = $4) requires that when $2 is given, it resolves to an
// action belonging to a retro of THIS household -- the same "fail closed on
// a value you did not construct" rule AddRetroActionAssignee below applies
// to membership ids. Without this, the FK alone would happily let a
// carried_from name another household's action, since a foreign key only
// proves the id exists somewhere in retro_actions, never that it belongs to
// the caller's household. $2 IS NULL short-circuits the check for a
// non-carried action (most of them): the LEFT JOINs then produce no match,
// cr.household_id is NULL, and the OR's first branch is what keeps the row.
func (q *Queries) AddRetroAction(ctx context.Context, arg AddRetroActionParams) (AddRetroActionRow, error) {
	row := q.db.QueryRow(ctx, addRetroAction,
		arg.Body,
		arg.CarriedFrom,
		arg.ID,
		arg.HouseholdID,
	)
	var i AddRetroActionRow
	err := row.Scan(
		&i.ID,
		&i.RetroID,
		&i.Body,
		&i.DoneAt,
		&i.CarriedFrom,
	)
	return i, err
}

const addRetroActionAssignee = `-- name: AddRetroActionAssignee :execrows
INSERT INTO retro_action_assignees (action_id, membership_id)
SELECT $1, m.id
FROM memberships m
WHERE m.id = $2 AND m.household_id = $3
ON CONFLICT (action_id, membership_id) DO UPDATE SET membership_id = excluded.membership_id
`

type AddRetroActionAssigneeParams struct {
	ActionID    pgtype.UUID
	ID          pgtype.UUID
	HouseholdID pgtype.UUID
}

// AddRetroActionAssignee inserts one owner, scoped through memberships the
// same way AddRetroAction scopes through retros: the SELECT's WHERE
// requires the membership to belong to household_id, so an id that is not a
// membership AT ALL and an id that IS a membership but of a DIFFERENT
// household both match zero rows. :execrows lets RetroActionRepo.Add see
// that zero and fail the whole transaction
// (usecase.RetroActionRepository.Add's own doc comment) rather than
// trusting retro_action_assignees.membership_id's foreign key alone, which
// only proves the id exists SOMEWHERE in memberships -- not that it belongs
// to this household.
//
// ON CONFLICT (action_id, membership_id) DO UPDATE, not DO NOTHING:
// RetroActionRepo.Add calls this once per id in AssigneeMembershipIDs
// WITHOUT deduping first, on purpose -- picking the same person twice in the
// modal is a redundant selection, not a state conflict, and this clause is
// what turns that literal repeat into a harmless no-op. But the household-
// membership rejection above and "the repeat succeeded" both still need
// :execrows's row count to mean something. DO NOTHING would return 0 rows
// affected on a duplicate pair exactly the same way a bad household match
// does, making the two indistinguishable to the Go caller; DO UPDATE SET
// membership_id = excluded.membership_id changes nothing about the stored
// row but Postgres still counts it as one row affected, so a genuine
// rejection (0 rows) stays distinguishable from an accepted, already-
// present pair (1 row). The PRIMARY KEY (action_id, membership_id) is what
// actually guarantees the row can never be duplicated in the table; this
// clause only stops that guarantee from surfacing as a raw 23505.
func (q *Queries) AddRetroActionAssignee(ctx context.Context, arg AddRetroActionAssigneeParams) (int64, error) {
	result, err := q.db.Exec(ctx, addRetroActionAssignee, arg.ActionID, arg.ID, arg.HouseholdID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeRetro = `-- name: CompleteRetro :one
UPDATE retros
SET completed_at = coalesce(completed_at, $3), updated_at = now()
WHERE household_id = $1 AND id = $2
RETURNING id, month, mood, went_well, was_hard, notes, completed_at, version
`

type CompleteRetroParams struct {
	HouseholdID pgtype.UUID
	ID          pgtype.UUID
	CompletedAt pgtype.Timestamptz
}

type CompleteRetroRow struct {
	ID          pgtype.UUID
	Month       pgtype.Date
	Mood        *int16
	WentWell    string
	WasHard     string
	Notes       string
	CompletedAt pgtype.Timestamptz
	Version     int32
}

// CompleteRetro stamps completed_at with the caller's `at`, but only when it
// is not already set -- coalesce keeps the FIRST completion time, the same
// "archiving is idempotent" shape SetGoalArchived and SetCategoryArchived
// already use, so finishing an already-finished retro is a harmless retry
// rather than a second, later timestamp overwriting the true one.
func (q *Queries) CompleteRetro(ctx context.Context, arg CompleteRetroParams) (CompleteRetroRow, error) {
	row := q.db.QueryRow(ctx, completeRetro, arg.HouseholdID, arg.ID, arg.CompletedAt)
	var i CompleteRetroRow
	err := row.Scan(
		&i.ID,
		&i.Month,
		&i.Mood,
		&i.WentWell,
		&i.WasHard,
		&i.Notes,
		&i.CompletedAt,
		&i.Version,
	)
	return i, err
}

const createRetro = `-- name: CreateRetro :one
INSERT INTO retros (household_id, month)
VALUES ($1, $2)
RETURNING id, month, mood, went_well, was_hard, notes, completed_at, version
`

type CreateRetroParams struct {
	HouseholdID pgtype.UUID
	Month       pgtype.Date
}

type CreateRetroRow struct {
	ID          pgtype.UUID
	Month       pgtype.Date
	Mood        *int16
	WentWell    string
	WasHard     string
	Notes       string
	CompletedAt pgtype.Timestamptz
	Version     int32
}

// CreateRetro writes an empty draft for the month. The UNIQUE (household_id,
// month) constraint (00009_retros.sql) is what makes a double-clicked "Start
// retro" button harmless -- the second insert fails with 23505, which
// translate maps to domain.ErrAlreadyExists rather than a raw pgx error
// (RetroRepository.Create's own doc comment).
func (q *Queries) CreateRetro(ctx context.Context, arg CreateRetroParams) (CreateRetroRow, error) {
	row := q.db.QueryRow(ctx, createRetro, arg.HouseholdID, arg.Month)
	var i CreateRetroRow
	err := row.Scan(
		&i.ID,
		&i.Month,
		&i.Mood,
		&i.WentWell,
		&i.WasHard,
		&i.Notes,
		&i.CompletedAt,
		&i.Version,
	)
	return i, err
}

const deleteDraftRetro = `-- name: DeleteDraftRetro :execrows
DELETE FROM retros
WHERE household_id = $1 AND id = $2 AND completed_at IS NULL
`

type DeleteDraftRetroParams struct {
	HouseholdID pgtype.UUID
	ID          pgtype.UUID
}

// DeleteDraftRetro removes a retro that has NOT been finished --
// completed_at IS NULL lives in the WHERE clause rather than a
// check-then-delete in Go, both because a check-then-delete can race and
// because :execrows lets RetroRepo.DeleteDraft see a zero-row match and
// refuse to call it success (DeleteDraft's own doc comment on
// RetroRepository, and the SetBillNextDue defect it cites).
func (q *Queries) DeleteDraftRetro(ctx context.Context, arg DeleteDraftRetroParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDraftRetro, arg.HouseholdID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRetroAction = `-- name: DeleteRetroAction :execrows
DELETE FROM retro_actions a
USING retros r
WHERE a.id = $2 AND a.retro_id = r.id AND r.household_id = $1
`

type DeleteRetroActionParams struct {
	HouseholdID pgtype.UUID
	ID          pgtype.UUID
}

// DeleteRetroAction hard-deletes one action, scoped through retros the same
// way SetRetroActionDone is -- carried_from's ON DELETE SET NULL
// (00009_retros.sql) means this can never orphan a later carried action.
// :execrows is what lets RetroActionRepo.Remove refuse a zero-row match
// instead of reporting success for nothing.
func (q *Queries) DeleteRetroAction(ctx context.Context, arg DeleteRetroActionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRetroAction, arg.HouseholdID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRetroByMonth = `-- name: GetRetroByMonth :one
SELECT id, month, mood, went_well, was_hard, notes, completed_at, version
FROM retros
WHERE household_id = $1 AND month = $2
`

type GetRetroByMonthParams struct {
	HouseholdID pgtype.UUID
	Month       pgtype.Date
}

type GetRetroByMonthRow struct {
	ID          pgtype.UUID
	Month       pgtype.Date
	Mood        *int16
	WentWell    string
	WasHard     string
	Notes       string
	CompletedAt pgtype.Timestamptz
	Version     int32
}

// GetRetroByMonth is ByMonth's whole implementation: household_id AND month
// both in the WHERE, so a retro belonging to another household is
// indistinguishable from one that was never created (RetroRepository's own
// package doc comment).
func (q *Queries) GetRetroByMonth(ctx context.Context, arg GetRetroByMonthParams) (GetRetroByMonthRow, error) {
	row := q.db.QueryRow(ctx, getRetroByMonth, arg.HouseholdID, arg.Month)
	var i GetRetroByMonthRow
	err := row.Scan(
		&i.ID,
		&i.Month,
		&i.Mood,
		&i.WentWell,
		&i.WasHard,
		&i.Notes,
		&i.CompletedAt,
		&i.Version,
	)
	return i, err
}

const listOpenActionsInMonth = `-- name: ListOpenActionsInMonth :many
SELECT a.id, a.retro_id, a.body, a.done_at, a.carried_from,
       COALESCE(array_agg(asg.membership_id) FILTER (WHERE asg.membership_id IS NOT NULL), '{}')::uuid[] AS assignee_ids
FROM retro_actions a
JOIN retros r ON r.id = a.retro_id
LEFT JOIN retro_action_assignees asg ON asg.action_id = a.id
WHERE r.household_id = $1 AND r.month = $2 AND a.done_at IS NULL
GROUP BY a.id, a.retro_id, a.body, a.done_at, a.carried_from
ORDER BY a.created_at, a.id
`

type ListOpenActionsInMonthParams struct {
	HouseholdID pgtype.UUID
	Month       pgtype.Date
}

type ListOpenActionsInMonthRow struct {
	ID          pgtype.UUID
	RetroID     pgtype.UUID
	Body        string
	DoneAt      pgtype.Timestamptz
	CarriedFrom pgtype.UUID
	AssigneeIds []pgtype.UUID
}

// ListOpenActionsInMonth is OpenInMonth's whole implementation: that
// month's actions with done_at IS NULL, scoped to household_id through the
// same retros join every query above uses. The caller is responsible for
// month already being the first of the calendar month, midnight UTC --
// OpenInMonth's own doc comment on RetroActionRepository -- this query does
// not renormalise it.
// Same GROUP BY / ORDER BY shape as ListRetroActions above, and the same
// reason a.created_at needs no entry in the GROUP BY list.
func (q *Queries) ListOpenActionsInMonth(ctx context.Context, arg ListOpenActionsInMonthParams) ([]ListOpenActionsInMonthRow, error) {
	rows, err := q.db.Query(ctx, listOpenActionsInMonth, arg.HouseholdID, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenActionsInMonthRow
	for rows.Next() {
		var i ListOpenActionsInMonthRow
		if err := rows.Scan(
			&i.ID,
			&i.RetroID,
			&i.Body,
			&i.DoneAt,
			&i.CarriedFrom,
			&i.AssigneeIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRetroActions = `-- name: ListRetroActions :many
SELECT a.id, a.retro_id, a.body, a.done_at, a.carried_from,
       COALESCE(array_agg(asg.membership_id) FILTER (WHERE asg.membership_id IS NOT NULL), '{}')::uuid[] AS assignee_ids
FROM retro_actions a
JOIN retros r ON r.id = a.retro_id
LEFT JOIN retro_action_assignees asg ON asg.action_id = a.id
WHERE r.household_id = $1 AND a.retro_id = $2
GROUP BY a.id, a.retro_id, a.body, a.done_at, a.carried_from
ORDER BY a.created_at, a.id
`

type ListRetroActionsParams struct {
	HouseholdID pgtype.UUID
	RetroID     pgtype.UUID
}

type ListRetroActionsRow struct {
	ID          pgtype.UUID
	RetroID     pgtype.UUID
	Body        string
	DoneAt      pgtype.Timestamptz
	CarriedFrom pgtype.UUID
	AssigneeIds []pgtype.UUID
}

// ListRetroActions is ForRetro's whole implementation: one row per action,
// each carrying its assignees folded into one array by a household-scoped
// LEFT JOIN + array_agg rather than a second query, and ORDER BY
// a.created_at, a.id because retro_actions carries no position column
// (00009_retros.sql's own comment) -- insertion order IS the order. The
// FILTER clause is what keeps an action with no assignees at '{}' rather
// than array_agg's default of a one-element array holding a single NULL.
// a.created_at is not in this list -- legal, not an oversight: a.id is
// (retro_actions' PRIMARY KEY), and grouping by a table's primary key lets
// Postgres treat every other column that is functionally dependent on it,
// created_at included, as already grouped. ORDER BY below is free to use it.
func (q *Queries) ListRetroActions(ctx context.Context, arg ListRetroActionsParams) ([]ListRetroActionsRow, error) {
	rows, err := q.db.Query(ctx, listRetroActions, arg.HouseholdID, arg.RetroID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRetroActionsRow
	for rows.Next() {
		var i ListRetroActionsRow
		if err := rows.Scan(
			&i.ID,
			&i.RetroID,
			&i.Body,
			&i.DoneAt,
			&i.CarriedFrom,
			&i.AssigneeIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRetros = `-- name: ListRetros :many
SELECT r.id, r.month, r.mood, r.went_well, r.was_hard, r.notes, r.completed_at, r.version,
       (SELECT count(*) FROM retro_actions a WHERE a.retro_id = r.id) AS action_count
FROM retros r
WHERE r.household_id = $1
ORDER BY r.month DESC
`

type ListRetrosRow struct {
	ID          pgtype.UUID
	Month       pgtype.Date
	Mood        *int16
	WentWell    string
	WasHard     string
	Notes       string
	CompletedAt pgtype.Timestamptz
	Version     int32
	ActionCount int64
}

// ListRetros returns every retro for a household, newest month first, each
// carrying its own action count via a correlated subquery rather than a
// JOIN + GROUP BY: a retro with zero actions must still appear exactly
// once, and a LEFT JOIN would need the same GROUP BY every other column
// goal.sql's ListGoalsWithTotals already carries for the identical reason.
// Deliberately unbounded -- List's own doc comment on RetroRepository.
func (q *Queries) ListRetros(ctx context.Context, householdID pgtype.UUID) ([]ListRetrosRow, error) {
	rows, err := q.db.Query(ctx, listRetros, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRetrosRow
	for rows.Next() {
		var i ListRetrosRow
		if err := rows.Scan(
			&i.ID,
			&i.Month,
			&i.Mood,
			&i.WentWell,
			&i.WasHard,
			&i.Notes,
			&i.CompletedAt,
			&i.Version,
			&i.ActionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRetroActionDone = `-- name: SetRetroActionDone :execrows
UPDATE retro_actions a
SET done_at = $3
FROM retros r
WHERE a.id = $2 AND a.retro_id = r.id AND r.household_id = $1
`

type SetRetroActionDoneParams struct {
	HouseholdID pgtype.UUID
	ID          pgtype.UUID
	DoneAt      pgtype.Timestamptz
}

// SetRetroActionDone ticks or unticks one action. done_at is passed straight
// through rather than branched in SQL: SetDone's own contract (clear the
// stamp on done=false, never record a "not done" time -- the port's own doc
// comment) is decided in Go, this query only ever sets the column to
// whatever it is given. UPDATE...FROM retros is the scoping clause, the
// same reason ListRetroActions joins through retros. :execrows lets
// RetroActionRepo.SetDone see a zero-row match and refuse to call it
// success -- the SetBillNextDue defect, docs/LEARNING.md.
func (q *Queries) SetRetroActionDone(ctx context.Context, arg SetRetroActionDoneParams) (int64, error) {
	result, err := q.db.Exec(ctx, setRetroActionDone, arg.HouseholdID, arg.ID, arg.DoneAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRetro = `-- name: UpdateRetro :one
UPDATE retros
SET mood = $3, went_well = $4, was_hard = $5, notes = $6,
    version = version + 1, updated_at = now()
WHERE household_id = $1 AND id = $2 AND version = $7
RETURNING id, month, mood, went_well, was_hard, notes, completed_at, version
`

type UpdateRetroParams struct {
	HouseholdID pgtype.UUID
	ID          pgtype.UUID
	Mood        *int16
	WentWell    string
	WasHard     string
	Notes       string
	Version     int32
}

type UpdateRetroRow struct {
	ID          pgtype.UUID
	Month       pgtype.Date
	Mood        *int16
	WentWell    string
	WasHard     string
	Notes       string
	CompletedAt pgtype.Timestamptz
	Version     int32
}

// UpdateRetro is the whole optimistic-concurrency guard. The version
// comparison is IN the WHERE clause, on purpose: a SELECT version followed
// by an UPDATE is two statements with a race window between them, and the
// version column exists to close exactly that window. Zero rows updated
// means either the retro is gone or the version moved since the editor
// loaded it, and RetroRepo.Update (not this query) is what tells the two
// apart, with one more cheap read.
func (q *Queries) UpdateRetro(ctx context.Context, arg UpdateRetroParams) (UpdateRetroRow, error) {
	row := q.db.QueryRow(ctx, updateRetro,
		arg.HouseholdID,
		arg.ID,
		arg.Mood,
		arg.WentWell,
		arg.WasHard,
		arg.Notes,
		arg.Version,
	)
	var i UpdateRetroRow
	err := row.Scan(
		&i.ID,
		&i.Month,
		&i.Mood,
		&i.WentWell,
		&i.WasHard,
		&i.Notes,
		&i.CompletedAt,
		&i.Version,
	)
	return i, err
}
