// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: retro.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeRetro = `-- name: CompleteRetro :one
UPDATE retros
SET completed_at = coalesce(completed_at, $3), updated_at = now()
WHERE household_id = $1 AND id = $2
RETURNING id, month, mood, went_well, was_hard, notes, completed_at, version
`

type CompleteRetroParams struct {
	HouseholdID pgtype.UUID
	ID          pgtype.UUID
	CompletedAt pgtype.Timestamptz
}

type CompleteRetroRow struct {
	ID          pgtype.UUID
	Month       pgtype.Date
	Mood        *int16
	WentWell    string
	WasHard     string
	Notes       string
	CompletedAt pgtype.Timestamptz
	Version     int32
}

// CompleteRetro stamps completed_at with the caller's `at`, but only when it
// is not already set -- coalesce keeps the FIRST completion time, the same
// "archiving is idempotent" shape SetGoalArchived and SetCategoryArchived
// already use, so finishing an already-finished retro is a harmless retry
// rather than a second, later timestamp overwriting the true one.
func (q *Queries) CompleteRetro(ctx context.Context, arg CompleteRetroParams) (CompleteRetroRow, error) {
	row := q.db.QueryRow(ctx, completeRetro, arg.HouseholdID, arg.ID, arg.CompletedAt)
	var i CompleteRetroRow
	err := row.Scan(
		&i.ID,
		&i.Month,
		&i.Mood,
		&i.WentWell,
		&i.WasHard,
		&i.Notes,
		&i.CompletedAt,
		&i.Version,
	)
	return i, err
}

const createRetro = `-- name: CreateRetro :one
INSERT INTO retros (household_id, month)
VALUES ($1, $2)
RETURNING id, month, mood, went_well, was_hard, notes, completed_at, version
`

type CreateRetroParams struct {
	HouseholdID pgtype.UUID
	Month       pgtype.Date
}

type CreateRetroRow struct {
	ID          pgtype.UUID
	Month       pgtype.Date
	Mood        *int16
	WentWell    string
	WasHard     string
	Notes       string
	CompletedAt pgtype.Timestamptz
	Version     int32
}

// CreateRetro writes an empty draft for the month. The UNIQUE (household_id,
// month) constraint (00009_retros.sql) is what makes a double-clicked "Start
// retro" button harmless -- the second insert fails with 23505, which
// translate maps to domain.ErrAlreadyExists rather than a raw pgx error
// (RetroRepository.Create's own doc comment).
func (q *Queries) CreateRetro(ctx context.Context, arg CreateRetroParams) (CreateRetroRow, error) {
	row := q.db.QueryRow(ctx, createRetro, arg.HouseholdID, arg.Month)
	var i CreateRetroRow
	err := row.Scan(
		&i.ID,
		&i.Month,
		&i.Mood,
		&i.WentWell,
		&i.WasHard,
		&i.Notes,
		&i.CompletedAt,
		&i.Version,
	)
	return i, err
}

const deleteDraftRetro = `-- name: DeleteDraftRetro :execrows
DELETE FROM retros
WHERE household_id = $1 AND id = $2 AND completed_at IS NULL
`

type DeleteDraftRetroParams struct {
	HouseholdID pgtype.UUID
	ID          pgtype.UUID
}

// DeleteDraftRetro removes a retro that has NOT been finished --
// completed_at IS NULL lives in the WHERE clause rather than a
// check-then-delete in Go, both because a check-then-delete can race and
// because :execrows lets RetroRepo.DeleteDraft see a zero-row match and
// refuse to call it success (DeleteDraft's own doc comment on
// RetroRepository, and the SetBillNextDue defect it cites).
func (q *Queries) DeleteDraftRetro(ctx context.Context, arg DeleteDraftRetroParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDraftRetro, arg.HouseholdID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRetroByMonth = `-- name: GetRetroByMonth :one
SELECT id, month, mood, went_well, was_hard, notes, completed_at, version
FROM retros
WHERE household_id = $1 AND month = $2
`

type GetRetroByMonthParams struct {
	HouseholdID pgtype.UUID
	Month       pgtype.Date
}

type GetRetroByMonthRow struct {
	ID          pgtype.UUID
	Month       pgtype.Date
	Mood        *int16
	WentWell    string
	WasHard     string
	Notes       string
	CompletedAt pgtype.Timestamptz
	Version     int32
}

// GetRetroByMonth is ByMonth's whole implementation: household_id AND month
// both in the WHERE, so a retro belonging to another household is
// indistinguishable from one that was never created (RetroRepository's own
// package doc comment).
func (q *Queries) GetRetroByMonth(ctx context.Context, arg GetRetroByMonthParams) (GetRetroByMonthRow, error) {
	row := q.db.QueryRow(ctx, getRetroByMonth, arg.HouseholdID, arg.Month)
	var i GetRetroByMonthRow
	err := row.Scan(
		&i.ID,
		&i.Month,
		&i.Mood,
		&i.WentWell,
		&i.WasHard,
		&i.Notes,
		&i.CompletedAt,
		&i.Version,
	)
	return i, err
}

const listRetros = `-- name: ListRetros :many
SELECT r.id, r.month, r.mood, r.went_well, r.was_hard, r.notes, r.completed_at, r.version,
       (SELECT count(*) FROM retro_actions a WHERE a.retro_id = r.id) AS action_count
FROM retros r
WHERE r.household_id = $1
ORDER BY r.month DESC
`

type ListRetrosRow struct {
	ID          pgtype.UUID
	Month       pgtype.Date
	Mood        *int16
	WentWell    string
	WasHard     string
	Notes       string
	CompletedAt pgtype.Timestamptz
	Version     int32
	ActionCount int64
}

// ListRetros returns every retro for a household, newest month first, each
// carrying its own action count via a correlated subquery rather than a
// JOIN + GROUP BY: a retro with zero actions must still appear exactly
// once, and a LEFT JOIN would need the same GROUP BY every other column
// goal.sql's ListGoalsWithTotals already carries for the identical reason.
// Deliberately unbounded -- List's own doc comment on RetroRepository.
func (q *Queries) ListRetros(ctx context.Context, householdID pgtype.UUID) ([]ListRetrosRow, error) {
	rows, err := q.db.Query(ctx, listRetros, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRetrosRow
	for rows.Next() {
		var i ListRetrosRow
		if err := rows.Scan(
			&i.ID,
			&i.Month,
			&i.Mood,
			&i.WentWell,
			&i.WasHard,
			&i.Notes,
			&i.CompletedAt,
			&i.Version,
			&i.ActionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRetro = `-- name: UpdateRetro :one
UPDATE retros
SET mood = $3, went_well = $4, was_hard = $5, notes = $6,
    version = version + 1, updated_at = now()
WHERE household_id = $1 AND id = $2 AND version = $7
RETURNING id, month, mood, went_well, was_hard, notes, completed_at, version
`

type UpdateRetroParams struct {
	HouseholdID pgtype.UUID
	ID          pgtype.UUID
	Mood        *int16
	WentWell    string
	WasHard     string
	Notes       string
	Version     int32
}

type UpdateRetroRow struct {
	ID          pgtype.UUID
	Month       pgtype.Date
	Mood        *int16
	WentWell    string
	WasHard     string
	Notes       string
	CompletedAt pgtype.Timestamptz
	Version     int32
}

// UpdateRetro is the whole optimistic-concurrency guard. The version
// comparison is IN the WHERE clause, on purpose: a SELECT version followed
// by an UPDATE is two statements with a race window between them, and the
// version column exists to close exactly that window. Zero rows updated
// means either the retro is gone or the version moved since the editor
// loaded it, and RetroRepo.Update (not this query) is what tells the two
// apart, with one more cheap read.
func (q *Queries) UpdateRetro(ctx context.Context, arg UpdateRetroParams) (UpdateRetroRow, error) {
	row := q.db.QueryRow(ctx, updateRetro,
		arg.HouseholdID,
		arg.ID,
		arg.Mood,
		arg.WentWell,
		arg.WasHard,
		arg.Notes,
		arg.Version,
	)
	var i UpdateRetroRow
	err := row.Scan(
		&i.ID,
		&i.Month,
		&i.Mood,
		&i.WentWell,
		&i.WasHard,
		&i.Notes,
		&i.CompletedAt,
		&i.Version,
	)
	return i, err
}
