// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: signup.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeSignup = `-- name: ConsumeSignup :one
UPDATE signups
SET consumed_at = now()
WHERE id = $1 AND consumed_at IS NULL AND expires_at > now()
RETURNING id, email
`

type ConsumeSignupRow struct {
	ID    pgtype.UUID
	Email string
}

// ConsumeSignup is the transactional gate for Provision. The guard lives here,
// in the UPDATE, rather than in the caller: a zero-rows result means the signup
// was already consumed or has expired, and that answer is authoritative for the
// race between SignupService.Complete's read and this write. It returns the
// email so Provision reads the verified address from the row it is already
// touching, rather than trusting one passed in by a caller.
func (q *Queries) ConsumeSignup(ctx context.Context, id pgtype.UUID) (ConsumeSignupRow, error) {
	row := q.db.QueryRow(ctx, consumeSignup, id)
	var i ConsumeSignupRow
	err := row.Scan(&i.ID, &i.Email)
	return i, err
}

const countSignupsForEmailSince = `-- name: CountSignupsForEmailSince :one
SELECT count(*) FROM signups
WHERE email = $1 AND created_at >= $2
`

type CountSignupsForEmailSinceParams struct {
	Email     string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CountSignupsForEmailSince(ctx context.Context, arg CountSignupsForEmailSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSignupsForEmailSince, arg.Email, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSignupsSince = `-- name: CountSignupsSince :one
SELECT count(*) FROM signups
WHERE created_at >= $1
`

func (q *Queries) CountSignupsSince(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countSignupsSince, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSignup = `-- name: CreateSignup :exec
INSERT INTO signups (email, token_hash, expires_at)
VALUES ($1, $2, $3)
`

type CreateSignupParams struct {
	Email     string
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSignup(ctx context.Context, arg CreateSignupParams) error {
	_, err := q.db.Exec(ctx, createSignup, arg.Email, arg.TokenHash, arg.ExpiresAt)
	return err
}

const getSignupByTokenHash = `-- name: GetSignupByTokenHash :one
SELECT id, email, expires_at, consumed_at
FROM signups
WHERE token_hash = $1
`

type GetSignupByTokenHashRow struct {
	ID         pgtype.UUID
	Email      string
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
}

func (q *Queries) GetSignupByTokenHash(ctx context.Context, tokenHash []byte) (GetSignupByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSignupByTokenHash, tokenHash)
	var i GetSignupByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const pruneSignups = `-- name: PruneSignups :execrows
DELETE FROM signups
WHERE created_at < $1
  AND (consumed_at IS NOT NULL OR expires_at <= now())
`

func (q *Queries) PruneSignups(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, pruneSignups, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
