// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: telegram.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeTelegramLinkRequest = `-- name: ConsumeTelegramLinkRequest :one
UPDATE telegram_link_requests
SET consumed_at = now(), chat_id = $2
WHERE nonce_hash = $1 AND consumed_at IS NULL AND expires_at > now()
RETURNING id
`

type ConsumeTelegramLinkRequestParams struct {
	NonceHash []byte
	ChatID    *int64
}

// ConsumeTelegramLinkRequest is the single-use gate, and it records the
// redeeming chat in the same statement. The guard lives here rather than in
// the caller for the same reason ConsumeSignup's does: zero rows is the
// authoritative answer to the race between a read and this write.
func (q *Queries) ConsumeTelegramLinkRequest(ctx context.Context, arg ConsumeTelegramLinkRequestParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, consumeTelegramLinkRequest, arg.NonceHash, arg.ChatID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const countTelegramLinksSince = `-- name: CountTelegramLinksSince :one
SELECT count(*) FROM telegram_link_requests
WHERE chat_id = $1 AND consumed_at >= $2
`

type CountTelegramLinksSinceParams struct {
	ChatID     *int64
	ConsumedAt pgtype.Timestamptz
}

func (q *Queries) CountTelegramLinksSince(ctx context.Context, arg CountTelegramLinksSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTelegramLinksSince, arg.ChatID, arg.ConsumedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTelegramAccount = `-- name: CreateTelegramAccount :exec
INSERT INTO telegram_accounts (user_id, chat_id) VALUES ($1, $2)
`

type CreateTelegramAccountParams struct {
	UserID pgtype.UUID
	ChatID int64
}

func (q *Queries) CreateTelegramAccount(ctx context.Context, arg CreateTelegramAccountParams) error {
	_, err := q.db.Exec(ctx, createTelegramAccount, arg.UserID, arg.ChatID)
	return err
}

const createTelegramLinkRequest = `-- name: CreateTelegramLinkRequest :exec
INSERT INTO telegram_link_requests (nonce_hash, expires_at)
VALUES ($1, $2)
`

type CreateTelegramLinkRequestParams struct {
	NonceHash []byte
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateTelegramLinkRequest(ctx context.Context, arg CreateTelegramLinkRequestParams) error {
	_, err := q.db.Exec(ctx, createTelegramLinkRequest, arg.NonceHash, arg.ExpiresAt)
	return err
}

const getTelegramAccountByChatID = `-- name: GetTelegramAccountByChatID :one
SELECT user_id FROM telegram_accounts WHERE chat_id = $1
`

func (q *Queries) GetTelegramAccountByChatID(ctx context.Context, chatID int64) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getTelegramAccountByChatID, chatID)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}
