// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transaction.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const categoryBelongsToHousehold = `-- name: CategoryBelongsToHousehold :one
SELECT EXISTS (
    SELECT 1 FROM categories
    WHERE id = $1 AND household_id = $2 AND archived_at IS NULL
)
`

type CategoryBelongsToHouseholdParams struct {
	ID          pgtype.UUID
	HouseholdID pgtype.UUID
}

// CategoryBelongsToHousehold answers whether a category is in this household,
// so a transaction can never reference one from another. It mirrors
// MembershipBelongsToHousehold, and exists for the same reason: the check must
// not be a Get that leaks whether the id exists elsewhere.
func (q *Queries) CategoryBelongsToHousehold(ctx context.Context, arg CategoryBelongsToHouseholdParams) (bool, error) {
	row := q.db.QueryRow(ctx, categoryBelongsToHousehold, arg.ID, arg.HouseholdID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countCategories = `-- name: CountCategories :one
SELECT count(*) FROM categories WHERE household_id = $1
`

func (q *Queries) CountCategories(ctx context.Context, householdID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCategories, householdID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    household_id, kind, occurred_on, description, category_id,
    paid_by_membership_id, from_account_id, to_account_id,
    amount_minor, amount_currency, received_amount_minor, received_amount_currency
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, household_id, kind, occurred_on, description, category_id,
          paid_by_membership_id, from_account_id, to_account_id,
          amount_minor, amount_currency, received_amount_minor,
          received_amount_currency, created_at
`

type CreateTransactionParams struct {
	HouseholdID            pgtype.UUID
	Kind                   string
	OccurredOn             pgtype.Date
	Description            string
	CategoryID             pgtype.UUID
	PaidByMembershipID     pgtype.UUID
	FromAccountID          pgtype.UUID
	ToAccountID            pgtype.UUID
	AmountMinor            int64
	AmountCurrency         string
	ReceivedAmountMinor    *int64
	ReceivedAmountCurrency *string
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.HouseholdID,
		arg.Kind,
		arg.OccurredOn,
		arg.Description,
		arg.CategoryID,
		arg.PaidByMembershipID,
		arg.FromAccountID,
		arg.ToAccountID,
		arg.AmountMinor,
		arg.AmountCurrency,
		arg.ReceivedAmountMinor,
		arg.ReceivedAmountCurrency,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Kind,
		&i.OccurredOn,
		&i.Description,
		&i.CategoryID,
		&i.PaidByMembershipID,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.AmountMinor,
		&i.AmountCurrency,
		&i.ReceivedAmountMinor,
		&i.ReceivedAmountCurrency,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :one
DELETE FROM transactions
WHERE household_id = $1 AND id = $2
RETURNING id
`

type DeleteTransactionParams struct {
	HouseholdID pgtype.UUID
	ID          pgtype.UUID
}

// DeleteTransaction is scoped by household_id like every other query here, and
// returns the id so the caller can tell "removed" from "there was nothing to
// remove" without a second round trip. A transaction is hard deleted -- unlike
// an account, nothing references it, so nothing is orphaned.
func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteTransaction, arg.HouseholdID, arg.ID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getCategoryKind = `-- name: GetCategoryKind :one
SELECT kind FROM categories WHERE id = $1 AND household_id = $2
`

type GetCategoryKindParams struct {
	ID          pgtype.UUID
	HouseholdID pgtype.UUID
}

func (q *Queries) GetCategoryKind(ctx context.Context, arg GetCategoryKindParams) (string, error) {
	row := q.db.QueryRow(ctx, getCategoryKind, arg.ID, arg.HouseholdID)
	var kind string
	err := row.Scan(&kind)
	return kind, err
}

const getTransaction = `-- name: GetTransaction :one

SELECT t.id, t.household_id, t.kind, t.occurred_on, t.description,
       t.category_id, t.paid_by_membership_id, t.from_account_id, t.to_account_id,
       t.amount_minor, t.amount_currency,
       t.received_amount_minor, t.received_amount_currency, t.created_at,
       c.name AS category_name,
       u.display_name AS paid_by_name,
       fa.nickname AS from_account_name,
       ta.nickname AS to_account_name,
       (fa.id IS NOT NULL AND t.occurred_on < fa.opening_balance_as_of) AS before_from_opening,
       (ta.id IS NOT NULL AND t.occurred_on < ta.opening_balance_as_of) AS before_to_opening
FROM transactions t
LEFT JOIN categories  c  ON c.id  = t.category_id
LEFT JOIN memberships m  ON m.id  = t.paid_by_membership_id
LEFT JOIN users       u  ON u.id  = m.user_id
LEFT JOIN accounts    fa ON fa.id = t.from_account_id
LEFT JOIN accounts    ta ON ta.id = t.to_account_id
WHERE t.household_id = $1 AND t.id = $2
`

type GetTransactionParams struct {
	HouseholdID pgtype.UUID
	ID          pgtype.UUID
}

type GetTransactionRow struct {
	ID                     pgtype.UUID
	HouseholdID            pgtype.UUID
	Kind                   string
	OccurredOn             pgtype.Date
	Description            string
	CategoryID             pgtype.UUID
	PaidByMembershipID     pgtype.UUID
	FromAccountID          pgtype.UUID
	ToAccountID            pgtype.UUID
	AmountMinor            int64
	AmountCurrency         string
	ReceivedAmountMinor    *int64
	ReceivedAmountCurrency *string
	CreatedAt              pgtype.Timestamptz
	CategoryName           *string
	PaidByName             *string
	FromAccountName        *string
	ToAccountName          *string
	BeforeFromOpening      *bool
	BeforeToOpening        *bool
}

// transactionColumns is repeated in full in each query below rather than
// factored into a view: sqlc generates a distinct row struct per query, and a
// view would hide which columns each one actually reads.
//
// The three LEFT JOINs are what let an expense (no destination), a shared
// transaction (no payer) and an uncategorised one come back as rows with NULL
// names rather than vanishing.
//
// before_from_opening and before_to_opening are computed here, next to the
// dates they compare, so the rule lives in one place. Strict < against
// opening_balance_as_of, mirroring the >= the balance sum uses in
// queries/account.sql: the opening balance is the figure at the START of
// its day (spec 2026-07-30, decision 1), so only a transaction dated
// strictly before it is already inside that figure and excluded.
func (q *Queries) GetTransaction(ctx context.Context, arg GetTransactionParams) (GetTransactionRow, error) {
	row := q.db.QueryRow(ctx, getTransaction, arg.HouseholdID, arg.ID)
	var i GetTransactionRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Kind,
		&i.OccurredOn,
		&i.Description,
		&i.CategoryID,
		&i.PaidByMembershipID,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.AmountMinor,
		&i.AmountCurrency,
		&i.ReceivedAmountMinor,
		&i.ReceivedAmountCurrency,
		&i.CreatedAt,
		&i.CategoryName,
		&i.PaidByName,
		&i.FromAccountName,
		&i.ToAccountName,
		&i.BeforeFromOpening,
		&i.BeforeToOpening,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, household_id, name, kind, sort_order, archived_at, created_at
FROM categories
WHERE household_id = $1 AND archived_at IS NULL
ORDER BY sort_order
`

func (q *Queries) ListCategories(ctx context.Context, householdID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Name,
			&i.Kind,
			&i.SortOrder,
			&i.ArchivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesIncludingArchived = `-- name: ListCategoriesIncludingArchived :many
SELECT id, household_id, name, kind, sort_order, archived_at, created_at
FROM categories
WHERE household_id = $1
ORDER BY sort_order
`

func (q *Queries) ListCategoriesIncludingArchived(ctx context.Context, householdID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesIncludingArchived, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Name,
			&i.Kind,
			&i.SortOrder,
			&i.ArchivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
SELECT t.id, t.household_id, t.kind, t.occurred_on, t.description,
       t.category_id, t.paid_by_membership_id, t.from_account_id, t.to_account_id,
       t.amount_minor, t.amount_currency,
       t.received_amount_minor, t.received_amount_currency, t.created_at,
       c.name AS category_name,
       u.display_name AS paid_by_name,
       fa.nickname AS from_account_name,
       ta.nickname AS to_account_name,
       (fa.id IS NOT NULL AND t.occurred_on < fa.opening_balance_as_of) AS before_from_opening,
       (ta.id IS NOT NULL AND t.occurred_on < ta.opening_balance_as_of) AS before_to_opening
FROM transactions t
LEFT JOIN categories  c  ON c.id  = t.category_id
LEFT JOIN memberships m  ON m.id  = t.paid_by_membership_id
LEFT JOIN users       u  ON u.id  = m.user_id
LEFT JOIN accounts    fa ON fa.id = t.from_account_id
LEFT JOIN accounts    ta ON ta.id = t.to_account_id
WHERE t.household_id = $1
  AND ($2::text IS NULL OR t.kind = $2::text)
  AND ($3::uuid IS NULL
       OR t.from_account_id = $3::uuid
       OR t.to_account_id   = $3::uuid)
  AND ($4::uuid IS NULL OR t.category_id = $4::uuid)
  AND ($5::uuid IS NULL OR t.paid_by_membership_id = $5::uuid)
  AND ($6::date IS NULL
       OR (t.occurred_on >= $6::date
           AND t.occurred_on < ($6::date + INTERVAL '1 month')))
  AND ($7::date IS NULL
       OR (t.occurred_on, t.id) < ($7::date, $8::uuid))
ORDER BY t.occurred_on DESC, t.id DESC
LIMIT $9
`

type ListTransactionsParams struct {
	HouseholdID pgtype.UUID
	Kind        *string
	AccountID   pgtype.UUID
	CategoryID  pgtype.UUID
	PaidBy      pgtype.UUID
	MonthStart  pgtype.Date
	CursorDate  pgtype.Date
	CursorID    pgtype.UUID
	RowLimit    int32
}

type ListTransactionsRow struct {
	ID                     pgtype.UUID
	HouseholdID            pgtype.UUID
	Kind                   string
	OccurredOn             pgtype.Date
	Description            string
	CategoryID             pgtype.UUID
	PaidByMembershipID     pgtype.UUID
	FromAccountID          pgtype.UUID
	ToAccountID            pgtype.UUID
	AmountMinor            int64
	AmountCurrency         string
	ReceivedAmountMinor    *int64
	ReceivedAmountCurrency *string
	CreatedAt              pgtype.Timestamptz
	CategoryName           *string
	PaidByName             *string
	FromAccountName        *string
	ToAccountName          *string
	BeforeFromOpening      *bool
	BeforeToOpening        *bool
}

// ListTransactions serves the ledger and all five of its filters.
//
// Each filter is written as `(sqlc.narg(x)::type IS NULL OR column = ...)`, so
// an unset filter is a no-op inside one prepared statement rather than a
// separate query per combination. Thirty-two hand-written variants would drift
// from each other, and a concatenated string would be an injection surface.
//
// The account filter matches EITHER side: a transfer belongs in the ledger of
// both accounts it touches.
//
// The keyset predicate is the row-value comparison (occurred_on, id) < (cursor
// date, cursor id), which matches transactions_household_date_idx exactly.
// Comparing the pair rather than the date alone is what makes two transactions
// on the same day page correctly.
//
// LIMIT is $N + 1 in the caller, not here: the extra row is how the caller
// learns another page exists without counting the table.
func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listTransactions,
		arg.HouseholdID,
		arg.Kind,
		arg.AccountID,
		arg.CategoryID,
		arg.PaidBy,
		arg.MonthStart,
		arg.CursorDate,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsRow
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Kind,
			&i.OccurredOn,
			&i.Description,
			&i.CategoryID,
			&i.PaidByMembershipID,
			&i.FromAccountID,
			&i.ToAccountID,
			&i.AmountMinor,
			&i.AmountCurrency,
			&i.ReceivedAmountMinor,
			&i.ReceivedAmountCurrency,
			&i.CreatedAt,
			&i.CategoryName,
			&i.PaidByName,
			&i.FromAccountName,
			&i.ToAccountName,
			&i.BeforeFromOpening,
			&i.BeforeToOpening,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const monthTotalsQuery = `-- name: MonthTotalsQuery :many
SELECT t.id, t.household_id, t.kind, t.occurred_on, t.description,
       t.category_id, t.paid_by_membership_id, t.from_account_id, t.to_account_id,
       t.amount_minor, t.amount_currency,
       t.received_amount_minor, t.received_amount_currency, t.created_at,
       c.name AS category_name,
       u.display_name AS paid_by_name,
       fa.nickname AS from_account_name,
       ta.nickname AS to_account_name,
       (fa.id IS NOT NULL AND t.occurred_on < fa.opening_balance_as_of) AS before_from_opening,
       (ta.id IS NOT NULL AND t.occurred_on < ta.opening_balance_as_of) AS before_to_opening
FROM transactions t
LEFT JOIN categories  c  ON c.id  = t.category_id
LEFT JOIN memberships m  ON m.id  = t.paid_by_membership_id
LEFT JOIN users       u  ON u.id  = m.user_id
LEFT JOIN accounts    fa ON fa.id = t.from_account_id
LEFT JOIN accounts    ta ON ta.id = t.to_account_id
WHERE t.household_id = $1
  AND t.occurred_on >= $2::date
  AND t.occurred_on < ($2::date + INTERVAL '1 month')
ORDER BY t.occurred_on DESC, t.id DESC
`

type MonthTotalsQueryParams struct {
	HouseholdID pgtype.UUID
	Column2     pgtype.Date
}

type MonthTotalsQueryRow struct {
	ID                     pgtype.UUID
	HouseholdID            pgtype.UUID
	Kind                   string
	OccurredOn             pgtype.Date
	Description            string
	CategoryID             pgtype.UUID
	PaidByMembershipID     pgtype.UUID
	FromAccountID          pgtype.UUID
	ToAccountID            pgtype.UUID
	AmountMinor            int64
	AmountCurrency         string
	ReceivedAmountMinor    *int64
	ReceivedAmountCurrency *string
	CreatedAt              pgtype.Timestamptz
	CategoryName           *string
	PaidByName             *string
	FromAccountName        *string
	ToAccountName          *string
	BeforeFromOpening      *bool
	BeforeToOpening        *bool
}

// MonthTotalsQuery returns every transaction in one calendar month. The
// service converts each amount into the household's primary currency before
// summing, which SQL cannot do -- the FX provider lives in the usecase layer.
func (q *Queries) MonthTotalsQuery(ctx context.Context, arg MonthTotalsQueryParams) ([]MonthTotalsQueryRow, error) {
	rows, err := q.db.Query(ctx, monthTotalsQuery, arg.HouseholdID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MonthTotalsQueryRow
	for rows.Next() {
		var i MonthTotalsQueryRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Kind,
			&i.OccurredOn,
			&i.Description,
			&i.CategoryID,
			&i.PaidByMembershipID,
			&i.FromAccountID,
			&i.ToAccountID,
			&i.AmountMinor,
			&i.AmountCurrency,
			&i.ReceivedAmountMinor,
			&i.ReceivedAmountCurrency,
			&i.CreatedAt,
			&i.CategoryName,
			&i.PaidByName,
			&i.FromAccountName,
			&i.ToAccountName,
			&i.BeforeFromOpening,
			&i.BeforeToOpening,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedCategories = `-- name: SeedCategories :exec
INSERT INTO categories (household_id, name, kind, sort_order)
VALUES
    ($1, $2, $3, $4),
    ($1, $5, $6, $7),
    ($1, $8, $9, $10),
    ($1, $11, $12, $13),
    ($1, $14, $15, $16),
    ($1, $17, $18, $19),
    ($1, $20, $21, $22),
    ($1, $23, $24, $25),
    ($1, $26, $27, $28),
    ($1, $29, $30, $31),
    ($1, $32, $33, $34),
    ($1, $35, $36, $37),
    ($1, $38, $39, $40)
ON CONFLICT (household_id, name) DO NOTHING
`

type SeedCategoriesParams struct {
	HouseholdID pgtype.UUID
	Name1       string
	Kind1       string
	SortOrder1  int32
	Name2       string
	Kind2       string
	SortOrder2  int32
	Name3       string
	Kind3       string
	SortOrder3  int32
	Name4       string
	Kind4       string
	SortOrder4  int32
	Name5       string
	Kind5       string
	SortOrder5  int32
	Name6       string
	Kind6       string
	SortOrder6  int32
	Name7       string
	Kind7       string
	SortOrder7  int32
	Name8       string
	Kind8       string
	SortOrder8  int32
	Name9       string
	Kind9       string
	SortOrder9  int32
	Name10      string
	Kind10      string
	SortOrder10 int32
	Name11      string
	Kind11      string
	SortOrder11 int32
	Name12      string
	Kind12      string
	SortOrder12 int32
	Name13      string
	Kind13      string
	SortOrder13 int32
}

// SeedCategories is one statement, not a read-then-write, and that is the
// whole point: two simultaneous first requests would both read "no categories"
// and both insert. ON CONFLICT DO NOTHING against UNIQUE (household_id, name)
// makes the loser of that race a no-op instead of a duplicate-key error.
//
// Thirteen literal VALUES rows, not unnest($2::text[], $3::text[], $4::int[]):
// sqlc's query analyzer does not carry the catalog entry for the multi-array
// form of unnest (real Postgres resolves it specially, not as an ordinary
// unnest(anyarray) overload), and rejects the query outright with "function
// unnest(unknown, unknown, unknown) does not exist". One round trip either
// way; the row count is pinned to len(domain.StarterCategories()) because
// this is a literal list, not a loop.
func (q *Queries) SeedCategories(ctx context.Context, arg SeedCategoriesParams) error {
	_, err := q.db.Exec(ctx, seedCategories,
		arg.HouseholdID,
		arg.Name1,
		arg.Kind1,
		arg.SortOrder1,
		arg.Name2,
		arg.Kind2,
		arg.SortOrder2,
		arg.Name3,
		arg.Kind3,
		arg.SortOrder3,
		arg.Name4,
		arg.Kind4,
		arg.SortOrder4,
		arg.Name5,
		arg.Kind5,
		arg.SortOrder5,
		arg.Name6,
		arg.Kind6,
		arg.SortOrder6,
		arg.Name7,
		arg.Kind7,
		arg.SortOrder7,
		arg.Name8,
		arg.Kind8,
		arg.SortOrder8,
		arg.Name9,
		arg.Kind9,
		arg.SortOrder9,
		arg.Name10,
		arg.Kind10,
		arg.SortOrder10,
		arg.Name11,
		arg.Kind11,
		arg.SortOrder11,
		arg.Name12,
		arg.Kind12,
		arg.SortOrder12,
		arg.Name13,
		arg.Kind13,
		arg.SortOrder13,
	)
	return err
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET kind                     = $3,
    occurred_on              = $4,
    description              = $5,
    category_id              = $6,
    paid_by_membership_id    = $7,
    from_account_id          = $8,
    to_account_id            = $9,
    amount_minor             = $10,
    amount_currency          = $11,
    received_amount_minor    = $12,
    received_amount_currency = $13
WHERE household_id = $1 AND id = $2
RETURNING id, household_id, kind, occurred_on, description, category_id,
          paid_by_membership_id, from_account_id, to_account_id,
          amount_minor, amount_currency, received_amount_minor,
          received_amount_currency, created_at
`

type UpdateTransactionParams struct {
	HouseholdID            pgtype.UUID
	ID                     pgtype.UUID
	Kind                   string
	OccurredOn             pgtype.Date
	Description            string
	CategoryID             pgtype.UUID
	PaidByMembershipID     pgtype.UUID
	FromAccountID          pgtype.UUID
	ToAccountID            pgtype.UUID
	AmountMinor            int64
	AmountCurrency         string
	ReceivedAmountMinor    *int64
	ReceivedAmountCurrency *string
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.HouseholdID,
		arg.ID,
		arg.Kind,
		arg.OccurredOn,
		arg.Description,
		arg.CategoryID,
		arg.PaidByMembershipID,
		arg.FromAccountID,
		arg.ToAccountID,
		arg.AmountMinor,
		arg.AmountCurrency,
		arg.ReceivedAmountMinor,
		arg.ReceivedAmountCurrency,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Kind,
		&i.OccurredOn,
		&i.Description,
		&i.CategoryID,
		&i.PaidByMembershipID,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.AmountMinor,
		&i.AmountCurrency,
		&i.ReceivedAmountMinor,
		&i.ReceivedAmountCurrency,
		&i.CreatedAt,
	)
	return i, err
}
