// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transaction.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const categoryBelongsToHousehold = `-- name: CategoryBelongsToHousehold :one
SELECT EXISTS (
    SELECT 1 FROM categories
    WHERE id = $1 AND household_id = $2 AND archived_at IS NULL
)
`

type CategoryBelongsToHouseholdParams struct {
	ID          pgtype.UUID
	HouseholdID pgtype.UUID
}

// CategoryBelongsToHousehold answers whether a category is in this household,
// so a transaction can never reference one from another. It mirrors
// MembershipBelongsToHousehold, and exists for the same reason: the check must
// not be a Get that leaks whether the id exists elsewhere.
func (q *Queries) CategoryBelongsToHousehold(ctx context.Context, arg CategoryBelongsToHouseholdParams) (bool, error) {
	row := q.db.QueryRow(ctx, categoryBelongsToHousehold, arg.ID, arg.HouseholdID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countCategories = `-- name: CountCategories :one
SELECT count(*) FROM categories WHERE household_id = $1
`

func (q *Queries) CountCategories(ctx context.Context, householdID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCategories, householdID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCategoryKind = `-- name: GetCategoryKind :one
SELECT kind FROM categories WHERE id = $1 AND household_id = $2
`

type GetCategoryKindParams struct {
	ID          pgtype.UUID
	HouseholdID pgtype.UUID
}

func (q *Queries) GetCategoryKind(ctx context.Context, arg GetCategoryKindParams) (string, error) {
	row := q.db.QueryRow(ctx, getCategoryKind, arg.ID, arg.HouseholdID)
	var kind string
	err := row.Scan(&kind)
	return kind, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, household_id, name, kind, sort_order, archived_at, created_at
FROM categories
WHERE household_id = $1 AND archived_at IS NULL
ORDER BY sort_order
`

func (q *Queries) ListCategories(ctx context.Context, householdID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Name,
			&i.Kind,
			&i.SortOrder,
			&i.ArchivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesIncludingArchived = `-- name: ListCategoriesIncludingArchived :many
SELECT id, household_id, name, kind, sort_order, archived_at, created_at
FROM categories
WHERE household_id = $1
ORDER BY sort_order
`

func (q *Queries) ListCategoriesIncludingArchived(ctx context.Context, householdID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesIncludingArchived, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Name,
			&i.Kind,
			&i.SortOrder,
			&i.ArchivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedCategories = `-- name: SeedCategories :exec
INSERT INTO categories (household_id, name, kind, sort_order)
VALUES
    ($1, $2, $3, $4),
    ($1, $5, $6, $7),
    ($1, $8, $9, $10),
    ($1, $11, $12, $13),
    ($1, $14, $15, $16),
    ($1, $17, $18, $19),
    ($1, $20, $21, $22),
    ($1, $23, $24, $25),
    ($1, $26, $27, $28),
    ($1, $29, $30, $31),
    ($1, $32, $33, $34),
    ($1, $35, $36, $37),
    ($1, $38, $39, $40)
ON CONFLICT (household_id, name) DO NOTHING
`

type SeedCategoriesParams struct {
	HouseholdID pgtype.UUID
	Name1       string
	Kind1       string
	SortOrder1  int32
	Name2       string
	Kind2       string
	SortOrder2  int32
	Name3       string
	Kind3       string
	SortOrder3  int32
	Name4       string
	Kind4       string
	SortOrder4  int32
	Name5       string
	Kind5       string
	SortOrder5  int32
	Name6       string
	Kind6       string
	SortOrder6  int32
	Name7       string
	Kind7       string
	SortOrder7  int32
	Name8       string
	Kind8       string
	SortOrder8  int32
	Name9       string
	Kind9       string
	SortOrder9  int32
	Name10      string
	Kind10      string
	SortOrder10 int32
	Name11      string
	Kind11      string
	SortOrder11 int32
	Name12      string
	Kind12      string
	SortOrder12 int32
	Name13      string
	Kind13      string
	SortOrder13 int32
}

// SeedCategories is one statement, not a read-then-write, and that is the
// whole point: two simultaneous first requests would both read "no categories"
// and both insert. ON CONFLICT DO NOTHING against UNIQUE (household_id, name)
// makes the loser of that race a no-op instead of a duplicate-key error.
//
// Thirteen literal VALUES rows, not unnest($2::text[], $3::text[], $4::int[]):
// sqlc's query analyzer does not carry the catalog entry for the multi-array
// form of unnest (real Postgres resolves it specially, not as an ordinary
// unnest(anyarray) overload), and rejects the query outright with "function
// unnest(unknown, unknown, unknown) does not exist". One round trip either
// way; the row count is pinned to len(domain.StarterCategories()) because
// this is a literal list, not a loop.
func (q *Queries) SeedCategories(ctx context.Context, arg SeedCategoriesParams) error {
	_, err := q.db.Exec(ctx, seedCategories,
		arg.HouseholdID,
		arg.Name1,
		arg.Kind1,
		arg.SortOrder1,
		arg.Name2,
		arg.Kind2,
		arg.SortOrder2,
		arg.Name3,
		arg.Kind3,
		arg.SortOrder3,
		arg.Name4,
		arg.Kind4,
		arg.SortOrder4,
		arg.Name5,
		arg.Kind5,
		arg.SortOrder5,
		arg.Name6,
		arg.Kind6,
		arg.SortOrder6,
		arg.Name7,
		arg.Kind7,
		arg.SortOrder7,
		arg.Name8,
		arg.Kind8,
		arg.SortOrder8,
		arg.Name9,
		arg.Kind9,
		arg.SortOrder9,
		arg.Name10,
		arg.Kind10,
		arg.SortOrder10,
		arg.Name11,
		arg.Kind11,
		arg.SortOrder11,
		arg.Name12,
		arg.Kind12,
		arg.SortOrder12,
		arg.Name13,
		arg.Kind13,
		arg.SortOrder13,
	)
	return err
}
