// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vision.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countGoalsInHousehold = `-- name: CountGoalsInHousehold :one
SELECT count(*) FROM goals
WHERE id = ANY($2::uuid[]) AND household_id = $1
`

type CountGoalsInHouseholdParams struct {
	HouseholdID pgtype.UUID
	GoalIds     []pgtype.UUID
}

// CountGoalsInHousehold answers how many of the given goal ids actually belong
// to this household. VisionRepo.Save compares this against the number of
// distinct ids it asked about, inside the same transaction as the write --
// vision_measures' own FK only proves a goal exists somewhere, never that it
// is this household's. The identical hole CountCategoriesInHousehold closes
// for budget lines.
func (q *Queries) CountGoalsInHousehold(ctx context.Context, arg CountGoalsInHouseholdParams) (int64, error) {
	row := q.db.QueryRow(ctx, countGoalsInHousehold, arg.HouseholdID, arg.GoalIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVision = `-- name: CreateVision :one
INSERT INTO visions (household_id, year, theme, description)
VALUES ($1, $2, $3, $4)
ON CONFLICT (household_id, year) DO NOTHING
RETURNING id, household_id, year, theme, description, version
`

type CreateVisionParams struct {
	HouseholdID pgtype.UUID
	Year        int16
	Theme       string
	Description string
}

type CreateVisionRow struct {
	ID          pgtype.UUID
	HouseholdID pgtype.UUID
	Year        int16
	Theme       string
	Description string
	Version     int32
}

// CreateVision is the version-0 path: a first save for a household-year.
// ON CONFLICT DO NOTHING rather than an upsert, so a zero-row result means
// "someone else created it while this editor was typing" and the repository
// can answer domain.ErrVisionChanged instead of silently overwriting a whole
// year of pillars.
//
// Both parent writes MUST return the post-write version: VisionRepo.Save
// hands it straight back as the token the next save will send, so a RETURNING
// list that gave back the version it read would make every subsequent save
// conflict against itself. Do not trim `version` from either RETURNING.
func (q *Queries) CreateVision(ctx context.Context, arg CreateVisionParams) (CreateVisionRow, error) {
	row := q.db.QueryRow(ctx, createVision,
		arg.HouseholdID,
		arg.Year,
		arg.Theme,
		arg.Description,
	)
	var i CreateVisionRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Year,
		&i.Theme,
		&i.Description,
		&i.Version,
	)
	return i, err
}

const deleteVisionMilestones = `-- name: DeleteVisionMilestones :exec
DELETE FROM vision_milestones WHERE vision_id = $1
`

func (q *Queries) DeleteVisionMilestones(ctx context.Context, visionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVisionMilestones, visionID)
	return err
}

const deleteVisionPillars = `-- name: DeleteVisionPillars :exec
DELETE FROM vision_pillars WHERE vision_id = $1
`

func (q *Queries) DeleteVisionPillars(ctx context.Context, visionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVisionPillars, visionID)
	return err
}

const getVision = `-- name: GetVision :one
SELECT id, household_id, year, theme, description, version
FROM visions
WHERE household_id = $1 AND year = $2
`

type GetVisionParams struct {
	HouseholdID pgtype.UUID
	Year        int16
}

type GetVisionRow struct {
	ID          pgtype.UUID
	HouseholdID pgtype.UUID
	Year        int16
	Theme       string
	Description string
	Version     int32
}

// GetVision reads one household-year's parent row. Scoped by household_id:
// a vision belonging to another household must be indistinguishable from one
// that does not exist.
func (q *Queries) GetVision(ctx context.Context, arg GetVisionParams) (GetVisionRow, error) {
	row := q.db.QueryRow(ctx, getVision, arg.HouseholdID, arg.Year)
	var i GetVisionRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Year,
		&i.Theme,
		&i.Description,
		&i.Version,
	)
	return i, err
}

const insertVisionMeasure = `-- name: InsertVisionMeasure :exec
INSERT INTO vision_measures (pillar_id, position, label, current_value, target_value, goal_id)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertVisionMeasureParams struct {
	PillarID     pgtype.UUID
	Position     int16
	Label        string
	CurrentValue *int32
	TargetValue  *int32
	GoalID       pgtype.UUID
}

func (q *Queries) InsertVisionMeasure(ctx context.Context, arg InsertVisionMeasureParams) error {
	_, err := q.db.Exec(ctx, insertVisionMeasure,
		arg.PillarID,
		arg.Position,
		arg.Label,
		arg.CurrentValue,
		arg.TargetValue,
		arg.GoalID,
	)
	return err
}

const insertVisionMilestone = `-- name: InsertVisionMilestone :exec
INSERT INTO vision_milestones (vision_id, position, year, title, note)
VALUES ($1, $2, $3, $4, $5)
`

type InsertVisionMilestoneParams struct {
	VisionID pgtype.UUID
	Position int16
	Year     int16
	Title    string
	Note     string
}

func (q *Queries) InsertVisionMilestone(ctx context.Context, arg InsertVisionMilestoneParams) error {
	_, err := q.db.Exec(ctx, insertVisionMilestone,
		arg.VisionID,
		arg.Position,
		arg.Year,
		arg.Title,
		arg.Note,
	)
	return err
}

const insertVisionPillar = `-- name: InsertVisionPillar :one
INSERT INTO vision_pillars (vision_id, position, name, description)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertVisionPillarParams struct {
	VisionID    pgtype.UUID
	Position    int16
	Name        string
	Description string
}

func (q *Queries) InsertVisionPillar(ctx context.Context, arg InsertVisionPillarParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertVisionPillar,
		arg.VisionID,
		arg.Position,
		arg.Name,
		arg.Description,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listVisionMeasures = `-- name: ListVisionMeasures :many
SELECT m.id, m.pillar_id, m.position, m.label, m.current_value, m.target_value, m.goal_id
FROM vision_measures m
JOIN vision_pillars p ON p.id = m.pillar_id
WHERE p.vision_id = $1
ORDER BY p.position, m.position
`

// ListVisionMeasures returns every measure of every pillar of one vision in a
// single round trip, joined back to its pillar so the repository can group
// them without a query per pillar.
func (q *Queries) ListVisionMeasures(ctx context.Context, visionID pgtype.UUID) ([]VisionMeasure, error) {
	rows, err := q.db.Query(ctx, listVisionMeasures, visionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VisionMeasure
	for rows.Next() {
		var i VisionMeasure
		if err := rows.Scan(
			&i.ID,
			&i.PillarID,
			&i.Position,
			&i.Label,
			&i.CurrentValue,
			&i.TargetValue,
			&i.GoalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisionMilestones = `-- name: ListVisionMilestones :many
SELECT id, position, year, title, note
FROM vision_milestones
WHERE vision_id = $1
ORDER BY position
`

type ListVisionMilestonesRow struct {
	ID       pgtype.UUID
	Position int16
	Year     int16
	Title    string
	Note     string
}

func (q *Queries) ListVisionMilestones(ctx context.Context, visionID pgtype.UUID) ([]ListVisionMilestonesRow, error) {
	rows, err := q.db.Query(ctx, listVisionMilestones, visionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVisionMilestonesRow
	for rows.Next() {
		var i ListVisionMilestonesRow
		if err := rows.Scan(
			&i.ID,
			&i.Position,
			&i.Year,
			&i.Title,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisionPillars = `-- name: ListVisionPillars :many
SELECT id, position, name, description
FROM vision_pillars
WHERE vision_id = $1
ORDER BY position
`

type ListVisionPillarsRow struct {
	ID          pgtype.UUID
	Position    int16
	Name        string
	Description string
}

// ListVisionPillars returns a vision's pillars in the order the household
// sees them -- the design numbers them visibly ("Pillar 1", "Pillar 2"), so
// position is not an implementation detail.
func (q *Queries) ListVisionPillars(ctx context.Context, visionID pgtype.UUID) ([]ListVisionPillarsRow, error) {
	rows, err := q.db.Query(ctx, listVisionPillars, visionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVisionPillarsRow
	for rows.Next() {
		var i ListVisionPillarsRow
		if err := rows.Scan(
			&i.ID,
			&i.Position,
			&i.Name,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVision = `-- name: UpdateVision :one
UPDATE visions
SET theme = $3, description = $4, version = version + 1, updated_at = now()
WHERE household_id = $1 AND year = $2 AND version = $5
RETURNING id, household_id, year, theme, description, version
`

type UpdateVisionParams struct {
	HouseholdID pgtype.UUID
	Year        int16
	Theme       string
	Description string
	Version     int32
}

type UpdateVisionRow struct {
	ID          pgtype.UUID
	HouseholdID pgtype.UUID
	Year        int16
	Theme       string
	Description string
	Version     int32
}

// UpdateVision is the version-guarded path. A zero-row result is ambiguous
// (deleted, or the other partner saved first) and the caller re-reads to tell
// the two apart -- RetroRepo.Update's own comment gives the reasoning.
func (q *Queries) UpdateVision(ctx context.Context, arg UpdateVisionParams) (UpdateVisionRow, error) {
	row := q.db.QueryRow(ctx, updateVision,
		arg.HouseholdID,
		arg.Year,
		arg.Theme,
		arg.Description,
		arg.Version,
	)
	var i UpdateVisionRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Year,
		&i.Theme,
		&i.Description,
		&i.Version,
	)
	return i, err
}
